-- Phase 7.3: review-required tutor publication and privileged mentor/admin publication.
-- A published resource is immutable; later revisions begin as independent copies.

create table if not exists public.content_publication_events (
  id bigint generated by default as identity primary key,
  resource_type text not null,
  resource_id text not null,
  owner_id uuid not null,
  actor_id uuid not null,
  publication_mode text not null,
  notes text not null default '',
  published_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint content_publication_events_resource_type_check check (resource_type in ('exam', 'form')),
  constraint content_publication_events_resource_id_present check (btrim(resource_id) <> ''),
  constraint content_publication_events_mode_check check (
    publication_mode in ('review_approved', 'privileged_direct')
  ),
  constraint content_publication_events_metadata_check check (jsonb_typeof(metadata) = 'object')
);

create index if not exists content_publication_events_resource_idx
on public.content_publication_events (resource_type, resource_id, published_at desc);

create index if not exists content_publication_events_owner_idx
on public.content_publication_events (owner_id, published_at desc);

alter table public.exam_definitions
  add column if not exists publication_mode text not null default 'private',
  add column if not exists published_by uuid,
  add column if not exists published_at timestamptz;

update public.exam_definitions definition
set publication_mode = case
      when definition.review_status = 'approved' and definition.visibility = 'public'
        then 'review_approved'
      else 'private'
    end,
    published_by = case
      when definition.review_status = 'approved' and definition.visibility = 'public'
        then coalesce((
          select reviews.reviewer_id
          from public.exam_reviews reviews
          where reviews.exam_id = definition.id and reviews.decision = 'approved'
          order by reviews.reviewed_at desc
          limit 1
        ), definition.owner_id)
      else null
    end,
    published_at = case
      when definition.review_status = 'approved' and definition.visibility = 'public'
        then definition.updated_at
      else null
    end;

alter table public.exam_definitions drop constraint if exists exam_definitions_publication_mode_check;
alter table public.exam_definitions add constraint exam_definitions_publication_mode_check check (
  publication_mode in ('private', 'review_approved', 'privileged_direct')
);
alter table public.exam_definitions drop constraint if exists exam_definitions_publication_state_check;
alter table public.exam_definitions add constraint exam_definitions_publication_state_check check (
  (
    review_status = 'approved'
    and visibility = 'public'
    and publication_mode in ('review_approved', 'privileged_direct')
    and published_by is not null
    and published_at is not null
  )
  or (
    review_status <> 'approved'
    and visibility = 'private'
    and publication_mode = 'private'
    and published_by is null
    and published_at is null
  )
);

alter table public.form_definitions
  add column if not exists review_status text not null default 'draft',
  add column if not exists visibility text not null default 'private',
  add column if not exists publication_mode text not null default 'private',
  add column if not exists published_by uuid,
  add column if not exists published_at timestamptz;

alter table public.form_definitions drop constraint if exists form_definitions_review_status_check;
alter table public.form_definitions add constraint form_definitions_review_status_check check (
  review_status in ('draft', 'pending_review', 'approved', 'changes_requested', 'rejected')
);
alter table public.form_definitions drop constraint if exists form_definitions_visibility_check;
alter table public.form_definitions add constraint form_definitions_visibility_check check (
  visibility in ('private', 'public')
);
alter table public.form_definitions drop constraint if exists form_definitions_publication_mode_check;
alter table public.form_definitions add constraint form_definitions_publication_mode_check check (
  publication_mode in ('private', 'review_approved', 'privileged_direct')
);
alter table public.form_definitions drop constraint if exists form_definitions_publication_state_check;
alter table public.form_definitions add constraint form_definitions_publication_state_check check (
  (
    review_status = 'approved'
    and visibility = 'public'
    and publication_mode in ('review_approved', 'privileged_direct')
    and published_by is not null
    and published_at is not null
  )
  or (
    review_status <> 'approved'
    and visibility = 'private'
    and publication_mode = 'private'
    and published_by is null
    and published_at is null
  )
);

create index if not exists form_definitions_review_queue_idx
on public.form_definitions (review_status, updated_at)
where status = 'active';

create table if not exists public.form_reviews (
  id bigint generated by default as identity primary key,
  form_id text not null,
  owner_id uuid not null,
  reviewer_id uuid not null,
  decision text not null,
  notes text not null default '',
  reviewed_at timestamptz not null default now(),
  constraint form_reviews_form_id_present check (btrim(form_id) <> ''),
  constraint form_reviews_decision_check check (
    decision in ('approved', 'changes_requested', 'rejected')
  ),
  constraint form_reviews_notes_check check (
    decision = 'approved' or btrim(notes) <> ''
  )
);

create index if not exists form_reviews_form_reviewed_idx
on public.form_reviews (form_id, reviewed_at desc);

create index if not exists form_reviews_owner_reviewed_idx
on public.form_reviews (owner_id, reviewed_at desc);

create or replace function public.enforce_exam_definition_lifecycle()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  caller_is_reviewer boolean := false;
  caller_can_publish boolean := false;
  state_transition_allowed boolean := false;
  transition_time timestamptz := clock_timestamp();
begin
  caller_is_reviewer := public.authorization_user_has_capability(caller_id, 'exam.review');
  caller_can_publish := public.authorization_user_has_capability(caller_id, 'exam.publish');

  if tg_op = 'INSERT' then
    if new.status <> 'active'
      or new.review_status <> 'draft'
      or new.visibility <> 'private'
      or new.publication_mode <> 'private'
    then
      raise exception 'New exams must begin as private drafts.';
    end if;
    new.created_at := coalesce(new.created_at, transition_time);
    new.updated_at := new.created_at;
    new.archived_at := null;
    new.publication_mode := 'private';
    new.published_by := null;
    new.published_at := null;
    return new;
  end if;

  if new.id is distinct from old.id
    or new.owner_id is distinct from old.owner_id
    or new.created_at is distinct from old.created_at
  then
    raise exception 'Exam identity and ownership fields are immutable.';
  end if;
  if old.status = 'archived' then
    raise exception 'Archived exams cannot be overwritten. Open the exam as a copy instead.';
  end if;

  if new.review_status is distinct from old.review_status
    or new.visibility is distinct from old.visibility
  then
    if old.review_status = 'draft'
      and new.review_status = 'pending_review'
      and new.visibility = 'private'
      and caller_id = old.owner_id
      and public.authorization_user_has_capability(caller_id, 'exam.submit_review')
    then
      state_transition_allowed := true;
      new.publication_mode := 'private';
      new.published_by := null;
      new.published_at := null;
    elsif old.review_status = 'pending_review'
      and new.review_status in ('approved', 'changes_requested', 'rejected')
      and new.visibility = (case when new.review_status = 'approved' then 'public' else 'private' end)
      and caller_is_reviewer
    then
      state_transition_allowed := true;
      if new.review_status = 'approved' then
        new.publication_mode := 'review_approved';
        new.published_by := caller_id;
        new.published_at := transition_time;
      else
        new.publication_mode := 'private';
        new.published_by := null;
        new.published_at := null;
      end if;
    elsif old.review_status = 'draft'
      and new.review_status = 'approved'
      and new.visibility = 'public'
      and caller_id = old.owner_id
      and caller_can_publish
    then
      state_transition_allowed := true;
      new.publication_mode := 'privileged_direct';
      new.published_by := caller_id;
      new.published_at := transition_time;
    else
      raise exception 'The requested exam publication transition is not permitted.';
    end if;
  elsif new.publication_mode is distinct from old.publication_mode
    or new.published_by is distinct from old.published_by
    or new.published_at is distinct from old.published_at
  then
    raise exception 'Exam publication metadata is server-owned.';
  end if;

  if new.status = 'archived' then
    if old.review_status <> 'draft'
      or new.review_status <> 'draft'
      or new.visibility <> 'private'
      or new.publication_mode <> 'private'
      or new.bundle is distinct from old.bundle
    then
      raise exception 'Only the unchanged private draft can be archived.';
    end if;
  elsif new.status <> 'active' then
    raise exception 'The requested exam lifecycle transition is invalid.';
  end if;

  if new.bundle is distinct from old.bundle
    and old.review_status <> 'draft'
    and not state_transition_allowed
  then
    raise exception 'An exam under review or already published cannot be overwritten.';
  end if;

  new.updated_at := transition_time;
  if new.status = 'archived' then new.archived_at := new.updated_at;
  else new.archived_at := null;
  end if;
  return new;
end;
$$;

create or replace function public.enforce_form_definition_lifecycle()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  definition_version integer;
  caller_is_reviewer boolean := false;
  caller_can_publish boolean := false;
  state_transition_allowed boolean := false;
  transition_time timestamptz := clock_timestamp();
begin
  if jsonb_typeof(new.definition) <> 'object'
    or coalesce(new.definition ->> 'id', '') <> new.id
    or coalesce(new.definition ->> 'version', '') !~ '^[1-9][0-9]*$'
    or coalesce(jsonb_typeof(new.definition -> 'blocks'), '') <> 'array'
  then
    raise exception 'The form definition identity or schema version is invalid.';
  end if;

  definition_version := (new.definition ->> 'version')::integer;
  new.schema_version := definition_version;
  new.title := coalesce(new.definition #>> '{meta,title}', '');
  caller_is_reviewer := public.authorization_user_has_capability(caller_id, 'form.review');
  caller_can_publish := public.authorization_user_has_capability(caller_id, 'form.publish');

  if tg_op = 'INSERT' then
    if new.status <> 'active'
      or new.review_status <> 'draft'
      or new.visibility <> 'private'
      or new.publication_mode <> 'private'
    then
      raise exception 'New forms must begin as private drafts.';
    end if;
    new.created_at := transition_time;
    new.updated_at := new.created_at;
    new.archived_at := null;
    new.publication_mode := 'private';
    new.published_by := null;
    new.published_at := null;
    return new;
  end if;

  if new.id is distinct from old.id
    or new.owner_id is distinct from old.owner_id
    or new.created_at is distinct from old.created_at
  then
    raise exception 'Form identity and ownership fields are immutable.';
  end if;
  if old.status = 'archived' then
    raise exception 'Archived forms cannot be overwritten. Open the form as a copy instead.';
  end if;

  if new.review_status is distinct from old.review_status
    or new.visibility is distinct from old.visibility
  then
    if old.review_status = 'draft'
      and new.review_status = 'pending_review'
      and new.visibility = 'private'
      and caller_id = old.owner_id
      and public.authorization_user_has_capability(caller_id, 'form.submit_review')
    then
      state_transition_allowed := true;
      new.publication_mode := 'private';
      new.published_by := null;
      new.published_at := null;
    elsif old.review_status = 'pending_review'
      and new.review_status in ('approved', 'changes_requested', 'rejected')
      and new.visibility = (case when new.review_status = 'approved' then 'public' else 'private' end)
      and caller_is_reviewer
    then
      state_transition_allowed := true;
      if new.review_status = 'approved' then
        new.publication_mode := 'review_approved';
        new.published_by := caller_id;
        new.published_at := transition_time;
      else
        new.publication_mode := 'private';
        new.published_by := null;
        new.published_at := null;
      end if;
    elsif old.review_status = 'draft'
      and new.review_status = 'approved'
      and new.visibility = 'public'
      and caller_id = old.owner_id
      and caller_can_publish
    then
      state_transition_allowed := true;
      new.publication_mode := 'privileged_direct';
      new.published_by := caller_id;
      new.published_at := transition_time;
    else
      raise exception 'The requested form publication transition is not permitted.';
    end if;
  elsif new.publication_mode is distinct from old.publication_mode
    or new.published_by is distinct from old.published_by
    or new.published_at is distinct from old.published_at
  then
    raise exception 'Form publication metadata is server-owned.';
  end if;

  if new.status = 'archived' then
    if old.review_status <> 'draft'
      or new.review_status <> 'draft'
      or new.visibility <> 'private'
      or new.publication_mode <> 'private'
      or new.definition is distinct from old.definition
    then
      raise exception 'Only the unchanged private draft can be archived.';
    end if;
  elsif new.status <> 'active' then
    raise exception 'The requested form lifecycle transition is invalid.';
  end if;

  if new.definition is distinct from old.definition then
    if old.review_status <> 'draft' then
      raise exception 'A form under review or already published cannot be overwritten.';
    end if;
    if exists (
      select 1 from public.form_submissions
      where form_owner_id = old.owner_id and form_id = old.id
    ) then
      raise exception 'Forms with submissions cannot be overwritten. Open the form as a copy instead.';
    end if;
  end if;

  new.updated_at := transition_time;
  if new.status = 'archived' then new.archived_at := new.updated_at;
  else new.archived_at := null;
  end if;
  return new;
end;
$$;

create or replace function public.save_form_draft(p_definition jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  source_id text;
  existing_form public.form_definitions%rowtype;
  saved_form public.form_definitions%rowtype;
begin
  if caller_id is null then raise exception 'Authentication is required to save a form.'; end if;
  if not public.authorization_user_has_capability(caller_id, 'form.create') then
    raise exception 'Your assigned roles cannot create or edit forms.';
  end if;
  if coalesce(jsonb_typeof(p_definition), '') <> 'object'
    or coalesce(jsonb_typeof(p_definition -> 'blocks'), '') <> 'array'
    or coalesce(p_definition ->> 'version', '') !~ '^[1-9][0-9]*$'
  then
    raise exception 'A valid form definition is required.';
  end if;
  source_id := btrim(coalesce(p_definition ->> 'id', ''));
  if source_id = '' then raise exception 'The form ID is required.'; end if;

  select * into existing_form
  from public.form_definitions
  where id = source_id;
  if found then
    if existing_form.owner_id <> caller_id then raise exception 'This form belongs to another author.'; end if;
    if existing_form.status = 'archived' then
      raise exception 'Archived forms cannot be overwritten. Open the form as a copy instead.';
    end if;
    if existing_form.review_status <> 'draft' then
      raise exception 'A form under review or already published cannot be overwritten. Open it as a copy instead.';
    end if;
  end if;

  insert into public.form_definitions (
    id, owner_id, status, review_status, visibility, publication_mode,
    schema_version, title, definition, archived_at, published_by, published_at
  ) values (
    source_id, caller_id, 'active', 'draft', 'private', 'private',
    (p_definition ->> 'version')::integer,
    coalesce(p_definition #>> '{meta,title}', ''),
    p_definition, null, null, null
  )
  on conflict (id) do update set
    status = 'active',
    schema_version = excluded.schema_version,
    title = excluded.title,
    definition = excluded.definition,
    archived_at = null
  returning * into saved_form;

  return jsonb_build_object(
    'id', saved_form.id,
    'owner_id', saved_form.owner_id,
    'status', saved_form.status,
    'review_status', saved_form.review_status,
    'visibility', saved_form.visibility,
    'publication_mode', saved_form.publication_mode,
    'published_by', saved_form.published_by,
    'published_at', saved_form.published_at,
    'created_at', saved_form.created_at,
    'updated_at', saved_form.updated_at,
    'archived_at', saved_form.archived_at,
    'definition', saved_form.definition
  );
end;
$$;

create or replace function public.submit_form_for_review(p_form_id text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  source_form public.form_definitions%rowtype;
  submitted_form public.form_definitions%rowtype;
begin
  if caller_id is null then raise exception 'Authentication is required to submit a form.'; end if;
  if not public.authorization_user_has_capability(caller_id, 'form.submit_review') then
    raise exception 'Your assigned roles cannot submit forms for review.';
  end if;
  select * into source_form
  from public.form_definitions
  where id = btrim(coalesce(p_form_id, ''))
  for update;
  if not found then raise exception 'The form could not be found.'; end if;
  if source_form.owner_id <> caller_id then raise exception 'This form belongs to another author.'; end if;
  if source_form.status <> 'active'
    or source_form.review_status <> 'draft'
    or source_form.visibility <> 'private'
  then
    raise exception 'Only an active private draft can be submitted for review.';
  end if;
  if not exists (
    select 1 from jsonb_array_elements(source_form.definition -> 'blocks') block
    where block ->> 'kind' = 'question'
  ) then
    raise exception 'Add at least one question before submitting this form.';
  end if;

  update public.form_definitions
  set review_status = 'pending_review', visibility = 'private'
  where id = source_form.id
  returning * into submitted_form;
  return to_jsonb(submitted_form);
end;
$$;

create or replace function public.review_form(
  p_form_id text,
  p_decision text,
  p_notes text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_decision text := lower(btrim(coalesce(p_decision, '')));
  normalized_notes text := btrim(coalesce(p_notes, ''));
  source_form public.form_definitions%rowtype;
  reviewed_form public.form_definitions%rowtype;
  review_record public.form_reviews%rowtype;
  next_visibility text;
begin
  if caller_id is null then raise exception 'Authentication is required to review a form.'; end if;
  if not public.authorization_user_has_capability(caller_id, 'form.review') then
    raise exception 'Your assigned roles cannot review forms.';
  end if;
  if normalized_decision not in ('approved', 'changes_requested', 'rejected') then
    raise exception 'The form review decision is invalid.';
  end if;
  if normalized_decision <> 'approved' and normalized_notes = '' then
    raise exception 'Review notes are required when requesting changes or rejecting a form.';
  end if;

  select * into source_form
  from public.form_definitions
  where id = btrim(coalesce(p_form_id, ''))
  for update;
  if not found then raise exception 'The form could not be found.'; end if;
  if source_form.owner_id = caller_id then
    raise exception 'A submitted form must be reviewed by a different mentor or administrator.';
  end if;
  if source_form.status <> 'active' or source_form.review_status <> 'pending_review' then
    raise exception 'Only a form awaiting review can receive a decision.';
  end if;

  next_visibility := case when normalized_decision = 'approved' then 'public' else 'private' end;
  update public.form_definitions
  set review_status = normalized_decision, visibility = next_visibility
  where id = source_form.id
  returning * into reviewed_form;

  insert into public.form_reviews (
    form_id, owner_id, reviewer_id, decision, notes, reviewed_at
  ) values (
    source_form.id, source_form.owner_id, caller_id,
    normalized_decision, normalized_notes, reviewed_form.updated_at
  ) returning * into review_record;

  if normalized_decision = 'approved' then
    insert into public.content_publication_events (
      resource_type, resource_id, owner_id, actor_id, publication_mode, notes, published_at
    ) values (
      'form', source_form.id, source_form.owner_id, caller_id,
      'review_approved', normalized_notes, reviewed_form.published_at
    );
  end if;
  return jsonb_build_object('form', to_jsonb(reviewed_form), 'review', to_jsonb(review_record));
end;
$$;

create or replace function public.publish_form(
  p_form_id text,
  p_notes text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  source_form public.form_definitions%rowtype;
  published_form public.form_definitions%rowtype;
  normalized_notes text := btrim(coalesce(p_notes, ''));
begin
  if caller_id is null then raise exception 'Authentication is required to publish a form.'; end if;
  if not public.authorization_user_has_capability(caller_id, 'form.publish') then
    raise exception 'Only a mentor or administrator can publish a form directly.';
  end if;
  select * into source_form
  from public.form_definitions
  where id = btrim(coalesce(p_form_id, ''))
  for update;
  if not found then raise exception 'The form could not be found.'; end if;
  if source_form.owner_id <> caller_id then raise exception 'Only the form owner can publish this draft directly.'; end if;
  if source_form.status <> 'active'
    or source_form.review_status <> 'draft'
    or source_form.visibility <> 'private'
  then
    raise exception 'Only an active private draft can be published directly.';
  end if;
  if not exists (
    select 1 from jsonb_array_elements(source_form.definition -> 'blocks') block
    where block ->> 'kind' = 'question'
  ) then
    raise exception 'Add at least one question before publishing this form.';
  end if;

  update public.form_definitions
  set review_status = 'approved', visibility = 'public'
  where id = source_form.id
  returning * into published_form;
  insert into public.content_publication_events (
    resource_type, resource_id, owner_id, actor_id, publication_mode, notes, published_at
  ) values (
    'form', source_form.id, source_form.owner_id, caller_id,
    'privileged_direct', normalized_notes, published_form.published_at
  );
  return to_jsonb(published_form);
end;
$$;

create or replace function public.review_exam(
  p_exam_id text,
  p_decision text,
  p_notes text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_decision text := lower(btrim(coalesce(p_decision, '')));
  normalized_notes text := btrim(coalesce(p_notes, ''));
  source_exam public.exam_definitions%rowtype;
  reviewed_exam public.exam_definitions%rowtype;
  review_record public.exam_reviews%rowtype;
  trusted_bundle jsonb;
  next_visibility text;
begin
  if caller_id is null then raise exception 'Authentication is required to review an exam.'; end if;
  if not public.authorization_user_has_capability(caller_id, 'exam.review') then
    raise exception 'Your assigned roles cannot review exams.';
  end if;
  if normalized_decision not in ('approved', 'changes_requested', 'rejected') then
    raise exception 'The exam review decision is invalid.';
  end if;
  if normalized_decision <> 'approved' and normalized_notes = '' then
    raise exception 'Review notes are required when requesting changes or rejecting an exam.';
  end if;

  select * into source_exam
  from public.exam_definitions
  where id = btrim(coalesce(p_exam_id, ''))
  for update;
  if not found then raise exception 'The exam could not be found.'; end if;
  if source_exam.owner_id = caller_id then
    raise exception 'A submitted exam must be reviewed by a different mentor or administrator.';
  end if;
  if source_exam.status <> 'active' or source_exam.review_status <> 'pending_review' then
    raise exception 'Only an exam awaiting review can receive a decision.';
  end if;

  next_visibility := case when normalized_decision = 'approved' then 'public' else 'private' end;
  trusted_bundle := public.set_exam_bundle_review_state(
    source_exam.bundle, normalized_decision, next_visibility, normalized_decision = 'approved'
  );
  update public.exam_definitions
  set review_status = normalized_decision, visibility = next_visibility, bundle = trusted_bundle
  where id = source_exam.id
  returning * into reviewed_exam;

  update public.exam_questions
  set review_status = normalized_decision,
      classification_status = case when normalized_decision = 'approved' then 'reviewed' else classification_status end,
      content = case
        when normalized_decision = 'approved'
          then jsonb_set(content, '{classificationStatus}', to_jsonb('reviewed'::text), true)
        else content
      end,
      updated_at = reviewed_exam.updated_at
  where exam_id = source_exam.id;

  insert into public.exam_reviews (
    exam_id, owner_id, reviewer_id, decision, notes, reviewed_at
  ) values (
    source_exam.id, source_exam.owner_id, caller_id,
    normalized_decision, normalized_notes, reviewed_exam.updated_at
  ) returning * into review_record;

  if normalized_decision = 'approved' then
    insert into public.content_publication_events (
      resource_type, resource_id, owner_id, actor_id, publication_mode, notes, published_at
    ) values (
      'exam', source_exam.id, source_exam.owner_id, caller_id,
      'review_approved', normalized_notes, reviewed_exam.published_at
    );
  end if;
  return jsonb_build_object('exam', to_jsonb(reviewed_exam), 'review', to_jsonb(review_record));
end;
$$;

create or replace function public.publish_exam(
  p_exam_id text,
  p_notes text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  source_exam public.exam_definitions%rowtype;
  published_exam public.exam_definitions%rowtype;
  trusted_bundle jsonb;
  normalized_notes text := btrim(coalesce(p_notes, ''));
begin
  if caller_id is null then raise exception 'Authentication is required to publish an exam.'; end if;
  if not public.authorization_user_has_capability(caller_id, 'exam.publish') then
    raise exception 'Only a mentor or administrator can publish an exam directly.';
  end if;
  select * into source_exam
  from public.exam_definitions
  where id = btrim(coalesce(p_exam_id, ''))
  for update;
  if not found then raise exception 'The exam could not be found.'; end if;
  if source_exam.owner_id <> caller_id then raise exception 'Only the exam owner can publish this draft directly.'; end if;
  if source_exam.status <> 'active'
    or source_exam.review_status <> 'draft'
    or source_exam.visibility <> 'private'
  then
    raise exception 'Only an active private draft can be published directly.';
  end if;
  if not exists (select 1 from public.exam_questions where exam_id = source_exam.id) then
    raise exception 'Add at least one question before publishing this exam.';
  end if;
  if exists (
    select 1 from public.exam_questions
    where exam_id = source_exam.id and difficulty = 'unclassified'
  ) then
    raise exception 'Classify every question before publishing this exam.';
  end if;

  trusted_bundle := public.set_exam_bundle_review_state(
    source_exam.bundle, 'approved', 'public', true
  );
  update public.exam_definitions
  set review_status = 'approved', visibility = 'public', bundle = trusted_bundle
  where id = source_exam.id
  returning * into published_exam;
  update public.exam_questions
  set review_status = 'approved',
      classification_status = 'reviewed',
      content = jsonb_set(content, '{classificationStatus}', to_jsonb('reviewed'::text), true),
      updated_at = published_exam.updated_at
  where exam_id = source_exam.id;
  insert into public.content_publication_events (
    resource_type, resource_id, owner_id, actor_id, publication_mode, notes, published_at
  ) values (
    'exam', source_exam.id, source_exam.owner_id, caller_id,
    'privileged_direct', normalized_notes, published_exam.published_at
  );
  return to_jsonb(published_exam);
end;
$$;

alter table public.form_reviews enable row level security;
alter table public.content_publication_events enable row level security;

drop policy if exists "Tutors can read their own forms" on public.form_definitions;
drop policy if exists "Owners and capable reviewers can read forms" on public.form_definitions;
create policy "Owners and capable reviewers can read forms"
on public.form_definitions for select to authenticated
using (
  (select auth.uid()) = owner_id
  or public.current_user_has_capability('form.review')
);

drop policy if exists "Tutors can create their own forms" on public.form_definitions;
drop policy if exists "Authorized authors can create their own forms" on public.form_definitions;
drop policy if exists "Tutors can update their active forms" on public.form_definitions;
drop policy if exists "Owners can archive private draft forms" on public.form_definitions;
create policy "Owners can archive private draft forms"
on public.form_definitions for update to authenticated
using (
  (select auth.uid()) = owner_id
  and status = 'active'
  and review_status = 'draft'
  and visibility = 'private'
)
with check (
  (select auth.uid()) = owner_id
  and status = 'archived'
  and review_status = 'draft'
  and visibility = 'private'
);

drop policy if exists "Tutors can delete their archived forms" on public.form_definitions;
drop policy if exists "Owners can delete archived private draft forms" on public.form_definitions;
create policy "Owners can delete archived private draft forms"
on public.form_definitions for delete to authenticated
using (
  (select auth.uid()) = owner_id
  and status = 'archived'
  and review_status = 'draft'
  and visibility = 'private'
);

drop policy if exists "Participants can read related form reviews" on public.form_reviews;
create policy "Participants can read related form reviews"
on public.form_reviews for select to authenticated
using (
  (select auth.uid()) = owner_id
  or (select auth.uid()) = reviewer_id
  or public.current_user_has_capability('form.review')
);

drop policy if exists "Participants can read publication events" on public.content_publication_events;
create policy "Participants can read publication events"
on public.content_publication_events for select to authenticated
using (
  (select auth.uid()) = owner_id
  or (select auth.uid()) = actor_id
  or (resource_type = 'exam' and public.current_user_has_capability('exam.review'))
  or (resource_type = 'form' and public.current_user_has_capability('form.review'))
  or public.current_user_has_capability('authorization.manage')
);

revoke all on public.form_definitions from anon, authenticated;
grant select, delete on public.form_definitions to authenticated;
grant update (status) on public.form_definitions to authenticated;
revoke all on public.form_reviews from anon, authenticated;
grant select on public.form_reviews to authenticated;
revoke all on public.content_publication_events from anon, authenticated;
grant select on public.content_publication_events to authenticated;

revoke all on function public.save_form_draft(jsonb) from public, anon, authenticated;
revoke all on function public.submit_form_for_review(text) from public, anon, authenticated;
revoke all on function public.review_form(text, text, text) from public, anon, authenticated;
revoke all on function public.publish_form(text, text) from public, anon, authenticated;
revoke all on function public.publish_exam(text, text) from public, anon, authenticated;
grant execute on function public.save_form_draft(jsonb) to authenticated;
grant execute on function public.submit_form_for_review(text) to authenticated;
grant execute on function public.review_form(text, text, text) to authenticated;
grant execute on function public.publish_form(text, text) to authenticated;
grant execute on function public.publish_exam(text, text) to authenticated;

-- Keep the existing protected review RPC grant after replacing its implementation.
revoke all on function public.review_exam(text, text, text) from public, anon, authenticated;
grant execute on function public.review_exam(text, text, text) to authenticated;
