-- Phase 1.A: governed global location catalog and location-derived timezones.

alter table public.profile_locations
  drop constraint if exists profile_locations_unique_place;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profile_locations_provider_reference_key'
      and conrelid = 'public.profile_locations'::regclass
  ) then
    alter table public.profile_locations
      add constraint profile_locations_provider_reference_key
      unique (provider, provider_reference);
  end if;
end;
$$;

create index if not exists profile_locations_hierarchy_idx
on public.profile_locations (country_code, region_code, active, city_name, location_key);

create table if not exists public.profile_countries (
  country_code text primary key,
  country_name text not null,
  provider text not null default 'kelp',
  provider_reference text not null default '',
  source_revision text not null default '',
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profile_countries_code_check check (country_code ~ '^[A-Z]{2}$'),
  constraint profile_countries_name_check check (btrim(country_name) <> '' and char_length(country_name) <= 120)
);

create table if not exists public.profile_regions (
  country_code text not null references public.profile_countries(country_code) on delete restrict,
  region_code text not null,
  region_name text not null,
  region_type text not null default '',
  provider text not null default 'kelp',
  provider_reference text not null default '',
  source_revision text not null default '',
  active boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (country_code, region_code),
  constraint profile_regions_code_check check (btrim(region_code) <> '' and char_length(region_code) <= 40),
  constraint profile_regions_name_check check (btrim(region_name) <> '' and char_length(region_name) <= 160),
  constraint profile_regions_type_check check (char_length(region_type) <= 80)
);

create index if not exists profile_countries_picker_idx
on public.profile_countries (active, country_name, country_code);

create index if not exists profile_regions_picker_idx
on public.profile_regions (country_code, active, region_name, region_code);

create table if not exists public.profile_location_catalog_imports (
  id bigint generated by default as identity primary key,
  provider text not null,
  source_revision text not null,
  source_sha256 text not null,
  country_count integer not null,
  region_count integer not null,
  city_count integer not null,
  imported_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint profile_location_catalog_imports_counts_check check (
    country_count >= 0 and region_count >= 0 and city_count >= 0
  ),
  constraint profile_location_catalog_imports_sha_check check (source_sha256 ~ '^[a-f0-9]{64}$'),
  constraint profile_location_catalog_imports_metadata_check check (jsonb_typeof(metadata) = 'object')
);

insert into public.profile_countries (
  country_code, country_name, provider, provider_reference, source_revision, sort_order
)
select distinct on (location.country_code)
  location.country_code,
  location.country_name,
  location.provider,
  location.country_code,
  location.source_revision,
  location.sort_order
from public.profile_locations location
order by location.country_code, location.sort_order, location.location_key
on conflict (country_code) do update set
  country_name = excluded.country_name,
  active = true,
  updated_at = now();

insert into public.profile_regions (
  country_code, region_code, region_name, provider, provider_reference, source_revision, sort_order
)
select distinct on (location.country_code, location.region_code)
  location.country_code,
  location.region_code,
  location.region_name,
  location.provider,
  concat(location.country_code, ':', location.region_code),
  location.source_revision,
  location.sort_order
from public.profile_locations location
order by location.country_code, location.region_code, location.sort_order, location.location_key
on conflict (country_code, region_code) do update set
  region_name = excluded.region_name,
  active = true,
  updated_at = now();

drop trigger if exists profile_countries_set_updated_at on public.profile_countries;
create trigger profile_countries_set_updated_at before update on public.profile_countries
for each row execute function public.set_updated_at();

drop trigger if exists profile_regions_set_updated_at on public.profile_regions;
create trigger profile_regions_set_updated_at before update on public.profile_regions
for each row execute function public.set_updated_at();

comment on table public.profile_countries is
  'Governed country picker hierarchy populated by a reviewed server-side catalog import.';
comment on table public.profile_regions is
  'Governed state/region picker hierarchy populated by a reviewed server-side catalog import.';
comment on table public.profile_location_catalog_imports is
  'Non-secret provenance and row counts for completed governed location-catalog imports.';
comment on column public.user_preferences.time_zone is
  'Server-maintained cache of the IANA timezone from the account Profile location; not browser-editable.';

create or replace function public.list_profile_countries()
returns jsonb
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'code', country.country_code,
    'name', country.country_name
  ) order by country.country_name, country.country_code), '[]'::jsonb)
  from public.profile_countries country
  where country.active;
$$;

create or replace function public.list_profile_regions(p_country_code text)
returns jsonb
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'code', region.region_code,
    'name', region.region_name,
    'type', region.region_type
  ) order by region.region_name, region.region_code), '[]'::jsonb)
  from public.profile_regions region
  join public.profile_countries country on country.country_code = region.country_code
  where region.country_code = upper(btrim(coalesce(p_country_code, '')))
    and region.active
    and country.active;
$$;

create or replace function public.list_profile_cities(p_country_code text, p_region_code text)
returns jsonb
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
    'key', location.location_key,
    'countryCode', location.country_code,
    'countryName', location.country_name,
    'regionCode', location.region_code,
    'regionName', location.region_name,
    'cityName', location.city_name,
    'timeZone', location.time_zone
  ) order by location.city_name, location.location_key), '[]'::jsonb)
  from public.profile_locations location
  join public.profile_countries country on country.country_code = location.country_code
  join public.profile_regions region
    on region.country_code = location.country_code
   and region.region_code = location.region_code
  where location.country_code = upper(btrim(coalesce(p_country_code, '')))
    and location.region_code = btrim(coalesce(p_region_code, ''))
    and location.active
    and country.active
    and region.active;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  requested_location_key text := nullif(btrim(coalesce(new.raw_user_meta_data ->> 'location_key', '')), '');
  accepted_location_key text;
  accepted_time_zone text := 'UTC';
  accepted_birth_date date;
  completed_at_value timestamptz;
begin
  if requested_location_key is not null then
    select location.location_key, location.time_zone
      into accepted_location_key, accepted_time_zone
    from public.profile_locations location
    where location.location_key = requested_location_key and location.active;
  end if;

  begin
    accepted_birth_date := nullif(new.raw_user_meta_data ->> 'birth_date', '')::date;
  exception when invalid_text_representation or datetime_field_overflow then
    accepted_birth_date := null;
  end;

  if accepted_birth_date is not null and (
    accepted_birth_date > current_date or accepted_birth_date < current_date - interval '120 years'
  ) then accepted_birth_date := null; end if;

  if btrim(coalesce(new.raw_user_meta_data ->> 'full_name', '')) <> ''
    and accepted_birth_date is not null
    and accepted_location_key is not null
  then completed_at_value := now(); end if;

  insert into public.profiles (
    id, full_name, email, role, birth_date, location_key, profile_completed_at
  ) values (
    new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''), coalesce(new.email, ''),
    'student', accepted_birth_date, accepted_location_key, completed_at_value
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    email = excluded.email,
    birth_date = coalesce(public.profiles.birth_date, excluded.birth_date),
    location_key = coalesce(public.profiles.location_key, excluded.location_key),
    profile_completed_at = coalesce(public.profiles.profile_completed_at, excluded.profile_completed_at);

  insert into public.user_preferences (user_id, theme_key, time_zone, time_zone_confirmed_at)
  values (
    new.id, 'ocean', accepted_time_zone,
    case when accepted_location_key is not null then now() end
  )
  on conflict (user_id) do update set
    time_zone = case when accepted_location_key is not null then excluded.time_zone else public.user_preferences.time_zone end,
    time_zone_confirmed_at = case when accepted_location_key is not null then excluded.time_zone_confirmed_at else public.user_preferences.time_zone_confirmed_at end;

  return new;
end;
$$;

create or replace function public.get_my_profile_configuration()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  result jsonb;
begin
  if caller_id is null then raise exception 'Authentication is required.'; end if;
  select jsonb_build_object(
    'version', 2,
    'profile', jsonb_build_object(
      'id', profile.id, 'fullName', profile.full_name, 'email', profile.email,
      'birthDate', profile.birth_date, 'createdAt', profile.created_at, 'updatedAt', profile.updated_at,
      'joinedWeeks', greatest(0, floor(extract(epoch from (now() - profile.created_at)) / 604800))::integer,
      'profileCompletedAt', profile.profile_completed_at,
      'location', case when location.location_key is null then null else jsonb_build_object(
        'key', location.location_key, 'countryCode', location.country_code,
        'countryName', location.country_name, 'regionCode', location.region_code,
        'regionName', location.region_name, 'cityName', location.city_name,
        'timeZone', location.time_zone
      ) end
    ),
    'preferences', jsonb_build_object(
      'themeKey', coalesce(preferences.theme_key, 'ocean'),
      'timeZone', coalesce(location.time_zone, preferences.time_zone, 'UTC'),
      'timeZoneConfirmedAt', case when location.location_key is not null
        then coalesce(preferences.time_zone_confirmed_at, profile.updated_at) else null end,
      'timeZoneSource', case when location.location_key is not null then 'profile_location' else 'fallback' end,
      'schemaVersion', coalesce(preferences.schema_version, 1)
    ),
    'hobbies', coalesce((select jsonb_agg(jsonb_build_object(
      'key', option.option_key, 'name', option.display_name
    ) order by option.sort_order, option.option_key)
      from public.user_profile_option_selections selection
      join public.profile_option_definitions option
        on option.category = selection.category and option.option_key = selection.option_key
      where selection.user_id = caller_id and selection.category = 'hobby'), '[]'::jsonb),
    'learningGoals', coalesce((select jsonb_agg(jsonb_build_object(
      'key', option.option_key, 'name', option.display_name
    ) order by option.sort_order, option.option_key)
      from public.user_profile_option_selections selection
      join public.profile_option_definitions option
        on option.category = selection.category and option.option_key = selection.option_key
      where selection.user_id = caller_id and selection.category = 'learning_goal'), '[]'::jsonb),
    'learningSummary', jsonb_build_object(
      'status', 'awaiting_learning_domains', 'activeTutors', null,
      'completedClasses', null, 'completedCourses', null, 'tutoringMinutes', null
    )
  ) into result
  from public.profiles profile
  left join public.profile_locations location on location.location_key = profile.location_key
  left join public.user_preferences preferences on preferences.user_id = profile.id
  where profile.id = caller_id;
  if result is null then raise exception 'Your Profile could not be found.'; end if;
  return result;
end;
$$;

create or replace function public.save_my_student_profile(
  p_profile jsonb,
  p_hobby_keys text[] default array[]::text[],
  p_learning_goal_keys text[] default array[]::text[]
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  existing_profile public.profiles%rowtype;
  normalized_name text;
  requested_location_key text;
  requested_time_zone text;
  requested_birth_date date;
  normalized_hobbies text[];
  normalized_goals text[];
  changed_fields text[] := array[]::text[];
begin
  if caller_id is null or not public.authorization_user_has_capability(caller_id, 'workspace.student') then
    raise exception 'Your assigned roles cannot update a Student Profile.';
  end if;
  if p_profile is null or jsonb_typeof(p_profile) <> 'object' then
    raise exception 'The Profile update must be an object.';
  end if;
  select * into existing_profile from public.profiles where id = caller_id for update;
  if not found then raise exception 'Your Profile could not be found.'; end if;

  normalized_name := btrim(coalesce(p_profile ->> 'fullName', ''));
  if normalized_name = '' or char_length(normalized_name) > 160 then
    raise exception 'Full name is required and must contain at most 160 characters.';
  end if;
  requested_location_key := nullif(btrim(coalesce(p_profile ->> 'locationKey', '')), '');
  select location.time_zone into requested_time_zone
  from public.profile_locations location
  where location.location_key = requested_location_key and location.active;
  if requested_time_zone is null then
    raise exception 'Choose an available country, state, and city.';
  end if;

  if nullif(btrim(coalesce(p_profile ->> 'birthDate', '')), '') is not null then
    begin
      requested_birth_date := (p_profile ->> 'birthDate')::date;
    exception when invalid_text_representation or datetime_field_overflow then
      raise exception 'Birth date is invalid.';
    end;
  end if;
  if existing_profile.birth_date is not null and requested_birth_date is not null
    and requested_birth_date is distinct from existing_profile.birth_date
  then raise exception 'Birth date corrections require Support review.'; end if;
  requested_birth_date := coalesce(existing_profile.birth_date, requested_birth_date);
  if requested_birth_date is null or requested_birth_date > current_date
    or requested_birth_date < current_date - interval '120 years'
  then raise exception 'A valid birth date is required.'; end if;

  select coalesce(array_agg(value order by value), array[]::text[]) into normalized_hobbies
  from (select distinct lower(btrim(item)) as value
    from unnest(coalesce(p_hobby_keys, array[]::text[])) item where btrim(item) <> '') selected;
  select coalesce(array_agg(value order by value), array[]::text[]) into normalized_goals
  from (select distinct lower(btrim(item)) as value
    from unnest(coalesce(p_learning_goal_keys, array[]::text[])) item where btrim(item) <> '') selected;

  if cardinality(normalized_hobbies) > 12 then raise exception 'Choose at most 12 hobbies.'; end if;
  if cardinality(normalized_goals) > 8 then raise exception 'Choose at most 8 learning goals.'; end if;
  if cardinality(normalized_hobbies) <> (select count(*) from public.profile_option_definitions option
    where option.category = 'hobby' and option.active and option.option_key = any(normalized_hobbies))
  then raise exception 'One or more hobby choices are unavailable.'; end if;
  if cardinality(normalized_goals) <> (select count(*) from public.profile_option_definitions option
    where option.category = 'learning_goal' and option.active and option.option_key = any(normalized_goals))
  then raise exception 'One or more learning-goal choices are unavailable.'; end if;

  if normalized_name is distinct from existing_profile.full_name then
    changed_fields := array_append(changed_fields, 'full_name'); end if;
  if requested_location_key is distinct from existing_profile.location_key then
    changed_fields := array_append(changed_fields, 'location');
    changed_fields := array_append(changed_fields, 'time_zone');
  end if;
  if existing_profile.birth_date is null then changed_fields := array_append(changed_fields, 'birth_date'); end if;

  update public.profiles set
    full_name = normalized_name,
    birth_date = requested_birth_date,
    location_key = requested_location_key,
    profile_completed_at = coalesce(profile_completed_at, now())
  where id = caller_id;

  insert into public.user_preferences (user_id, theme_key, time_zone, time_zone_confirmed_at)
  values (caller_id, 'ocean', requested_time_zone, now())
  on conflict (user_id) do update set
    time_zone = excluded.time_zone,
    time_zone_confirmed_at = excluded.time_zone_confirmed_at;

  delete from public.user_profile_option_selections
  where user_id = caller_id and category in ('hobby', 'learning_goal');
  insert into public.user_profile_option_selections (user_id, category, option_key)
  select caller_id, 'hobby', item from unnest(normalized_hobbies) item;
  insert into public.user_profile_option_selections (user_id, category, option_key)
  select caller_id, 'learning_goal', item from unnest(normalized_goals) item;

  insert into public.profile_change_events (user_id, actor_user_id, event_type, changed_fields, metadata)
  values (
    caller_id, caller_id, 'profile_updated', changed_fields || array['hobbies', 'learning_goals'],
    jsonb_build_object('hobbyCount', cardinality(normalized_hobbies), 'learningGoalCount', cardinality(normalized_goals))
  );
  return public.get_my_profile_configuration();
end;
$$;

create or replace function public.save_my_preferences(p_preferences jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  requested_theme text;
begin
  if caller_id is null then raise exception 'Authentication is required.'; end if;
  if p_preferences is null or jsonb_typeof(p_preferences) <> 'object' then
    raise exception 'The preference update must be an object.';
  end if;
  if p_preferences ? 'timeZone' then
    raise exception 'Timezone is derived from the Profile country, state, and city.';
  end if;
  requested_theme := lower(btrim(coalesce(p_preferences ->> 'themeKey', '')));
  if not exists (select 1 from public.profile_theme_presets where theme_key = requested_theme and active)
  then raise exception 'Choose an available theme.'; end if;

  insert into public.user_preferences (user_id, theme_key)
  values (caller_id, requested_theme)
  on conflict (user_id) do update set theme_key = excluded.theme_key;

  insert into public.profile_change_events (user_id, actor_user_id, event_type, changed_fields)
  values (caller_id, caller_id, 'preferences_updated', array['theme']);
  return public.get_my_profile_configuration();
end;
$$;

create or replace function public.reset_my_preferences(p_scope text default 'all')
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_scope text := lower(btrim(coalesce(p_scope, 'all')));
begin
  if caller_id is null then raise exception 'Authentication is required.'; end if;
  if normalized_scope not in ('theme', 'all') then
    raise exception 'Only the theme can be reset from preferences.';
  end if;
  insert into public.user_preferences (user_id) values (caller_id)
  on conflict (user_id) do update set theme_key = 'ocean';
  update public.user_preferences set theme_key = 'ocean' where user_id = caller_id;
  insert into public.profile_change_events (user_id, actor_user_id, event_type, changed_fields, metadata)
  values (
    caller_id, caller_id, 'preferences_reset', array['theme'],
    jsonb_build_object('scope', normalized_scope)
  );
  return public.get_my_profile_configuration();
end;
$$;

update public.user_preferences preferences
set time_zone = location.time_zone,
    time_zone_confirmed_at = coalesce(preferences.time_zone_confirmed_at, now())
from public.profiles profile
join public.profile_locations location on location.location_key = profile.location_key
where preferences.user_id = profile.id
  and (preferences.time_zone is distinct from location.time_zone
    or preferences.time_zone_confirmed_at is null);

update public.profiles profile
set profile_completed_at = coalesce(profile.profile_completed_at, now())
where btrim(profile.full_name) <> ''
  and profile.birth_date is not null
  and profile.location_key is not null;

alter table public.profile_countries enable row level security;
alter table public.profile_regions enable row level security;
alter table public.profile_location_catalog_imports enable row level security;

revoke all on public.profile_countries from anon, authenticated;
revoke all on public.profile_regions from anon, authenticated;
revoke all on public.profile_location_catalog_imports from anon, authenticated;

grant all on public.profile_countries to service_role;
grant all on public.profile_regions to service_role;
grant all on public.profile_locations to service_role;
grant all on public.profile_location_catalog_imports to service_role;
grant usage, select on sequence public.profile_location_catalog_imports_id_seq to service_role;

revoke all on function public.list_profile_countries() from public, anon, authenticated;
revoke all on function public.list_profile_regions(text) from public, anon, authenticated;
revoke all on function public.list_profile_cities(text, text) from public, anon, authenticated;
grant execute on function public.list_profile_countries() to anon, authenticated;
grant execute on function public.list_profile_regions(text) to anon, authenticated;
grant execute on function public.list_profile_cities(text, text) to anon, authenticated;
grant execute on function public.list_profile_countries() to service_role;
grant execute on function public.list_profile_regions(text) to service_role;
grant execute on function public.list_profile_cities(text, text) to service_role;

comment on function public.list_profile_countries() is
  'Returns only active governed countries. City data is requested after country and region selection.';
comment on function public.list_profile_regions(text) is
  'Returns only active governed regions for one governed country.';
comment on function public.list_profile_cities(text, text) is
  'Returns only active governed cities and their server-owned timezone for one country and region.';
