-- Phase 4: governed curriculum taxonomy foundation.
-- Canonical nodes use a flexible hierarchy:
-- degree -> subject -> track -> topic -> topic (to any useful depth).

create table if not exists public.curriculum_nodes (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid references public.curriculum_nodes(id) on delete restrict,
  node_type text not null,
  name text not null,
  slug text not null,
  description text not null default '',
  status text not null default 'active',
  sort_order integer not null default 100,
  created_by uuid references public.profiles(id) on delete set null,
  approved_by uuid references public.profiles(id) on delete set null,
  source_proposal_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint curriculum_nodes_type_check check (
    node_type in ('degree', 'subject', 'track', 'topic')
  ),
  constraint curriculum_nodes_name_present check (btrim(name) <> ''),
  constraint curriculum_nodes_slug_check check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint curriculum_nodes_status_check check (status in ('active', 'archived')),
  constraint curriculum_nodes_archive_check check (
    (status = 'active' and archived_at is null)
    or (status = 'archived' and archived_at is not null)
  ),
  constraint curriculum_nodes_metadata_check check (jsonb_typeof(metadata) = 'object'),
  constraint curriculum_nodes_not_own_parent check (parent_id is null or parent_id <> id)
);

create unique index if not exists curriculum_nodes_active_root_slug_idx
on public.curriculum_nodes (slug)
where parent_id is null and status = 'active';

create unique index if not exists curriculum_nodes_active_sibling_slug_idx
on public.curriculum_nodes (parent_id, slug)
where parent_id is not null and status = 'active';

create index if not exists curriculum_nodes_parent_order_idx
on public.curriculum_nodes (parent_id, status, sort_order, name);

create table if not exists public.curriculum_taxonomy_proposals (
  id uuid primary key default gen_random_uuid(),
  proposer_id uuid not null references public.profiles(id) on delete restrict,
  parent_id uuid references public.curriculum_nodes(id) on delete restrict,
  node_type text not null,
  name text not null,
  slug text not null,
  description text not null default '',
  status text not null default 'pending',
  reviewer_id uuid references public.profiles(id) on delete set null,
  review_notes text not null default '',
  applied_node_id uuid references public.curriculum_nodes(id) on delete set null,
  submitted_at timestamptz not null default now(),
  decided_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint curriculum_taxonomy_proposals_type_check check (
    node_type in ('degree', 'subject', 'track', 'topic')
  ),
  constraint curriculum_taxonomy_proposals_name_present check (btrim(name) <> ''),
  constraint curriculum_taxonomy_proposals_slug_check check (
    slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'
  ),
  constraint curriculum_taxonomy_proposals_status_check check (
    status in ('pending', 'approved', 'rejected')
  ),
  constraint curriculum_taxonomy_proposals_decision_check check (
    (status = 'pending' and reviewer_id is null and decided_at is null and applied_node_id is null)
    or (status = 'approved' and reviewer_id is not null and decided_at is not null and applied_node_id is not null)
    or (status = 'rejected' and reviewer_id is not null and decided_at is not null and applied_node_id is null)
  ),
  constraint curriculum_taxonomy_proposals_metadata_check check (jsonb_typeof(metadata) = 'object')
);

alter table public.curriculum_nodes
  drop constraint if exists curriculum_nodes_source_proposal_fkey;
alter table public.curriculum_nodes
  add constraint curriculum_nodes_source_proposal_fkey
  foreign key (source_proposal_id)
  references public.curriculum_taxonomy_proposals(id)
  on delete set null;

create index if not exists curriculum_taxonomy_proposals_queue_idx
on public.curriculum_taxonomy_proposals (status, submitted_at, id);

create index if not exists curriculum_taxonomy_proposals_owner_idx
on public.curriculum_taxonomy_proposals (proposer_id, submitted_at desc);

create table if not exists public.curriculum_taxonomy_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  node_id uuid references public.curriculum_nodes(id) on delete set null,
  proposal_id uuid references public.curriculum_taxonomy_proposals(id) on delete set null,
  actor_id uuid references public.profiles(id) on delete set null,
  occurred_at timestamptz not null default now(),
  details jsonb not null default '{}'::jsonb,
  constraint curriculum_taxonomy_events_type_check check (
    event_type in ('node_created', 'node_updated', 'node_archived', 'proposal_submitted', 'proposal_approved', 'proposal_rejected')
  ),
  constraint curriculum_taxonomy_events_details_check check (jsonb_typeof(details) = 'object')
);

create index if not exists curriculum_taxonomy_events_recent_idx
on public.curriculum_taxonomy_events (occurred_at desc, id desc);

create or replace function public.normalize_curriculum_slug(p_value text)
returns text
language sql
immutable
set search_path = pg_catalog
as $$
  select trim(both '-' from regexp_replace(
    lower(btrim(coalesce(p_value, ''))),
    '[^a-z0-9]+',
    '-',
    'g'
  ));
$$;

create or replace function public.assert_curriculum_parent(
  p_parent_id uuid,
  p_node_type text
)
returns void
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  normalized_type text := lower(btrim(coalesce(p_node_type, '')));
  parent_node public.curriculum_nodes%rowtype;
begin
  if normalized_type not in ('degree', 'subject', 'track', 'topic') then
    raise exception 'The curriculum node type is invalid.';
  end if;

  if p_parent_id is null then
    if normalized_type <> 'degree' then
      raise exception 'Only a degree can be a root curriculum node.';
    end if;
    return;
  end if;

  select * into parent_node
  from public.curriculum_nodes
  where id = p_parent_id and status = 'active';
  if not found then
    raise exception 'The selected parent curriculum node is not active.';
  end if;

  if (parent_node.node_type = 'degree' and normalized_type <> 'subject')
    or (parent_node.node_type = 'subject' and normalized_type <> 'track')
    or (parent_node.node_type in ('track', 'topic') and normalized_type <> 'topic')
  then
    raise exception 'The selected parent does not accept this curriculum node type.';
  end if;
end;
$$;

create or replace function public.next_curriculum_sort_order(p_parent_id uuid)
returns integer
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select coalesce(max(sort_order), 0) + 10
  from public.curriculum_nodes
  where parent_id is not distinct from p_parent_id and status = 'active';
$$;

create or replace function public.create_curriculum_node(
  p_parent_id uuid,
  p_node_type text,
  p_name text,
  p_description text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_type text := lower(btrim(coalesce(p_node_type, '')));
  normalized_name text := btrim(coalesce(p_name, ''));
  normalized_slug text;
  created_node public.curriculum_nodes%rowtype;
begin
  if caller_id is null
    or not public.authorization_user_has_capability(caller_id, 'taxonomy.manage')
  then
    raise exception 'Only a taxonomy administrator can add canonical curriculum nodes.';
  end if;
  if normalized_name = '' or length(normalized_name) > 140 then
    raise exception 'A curriculum node name between 1 and 140 characters is required.';
  end if;
  normalized_slug := public.normalize_curriculum_slug(normalized_name);
  if normalized_slug = '' then
    raise exception 'The curriculum node name must contain letters or numbers.';
  end if;
  perform public.assert_curriculum_parent(p_parent_id, normalized_type);

  insert into public.curriculum_nodes (
    parent_id, node_type, name, slug, description, sort_order,
    created_by, approved_by, metadata
  ) values (
    p_parent_id, normalized_type, normalized_name, normalized_slug,
    btrim(coalesce(p_description, '')),
    public.next_curriculum_sort_order(p_parent_id), caller_id, caller_id,
    jsonb_build_object('creationMode', 'administrator_direct')
  )
  returning * into created_node;

  insert into public.curriculum_taxonomy_events (
    event_type, node_id, actor_id, details
  ) values (
    'node_created', created_node.id, caller_id,
    jsonb_build_object('mode', 'administrator_direct')
  );
  return to_jsonb(created_node);
exception
  when unique_violation then
    raise exception 'An active curriculum node with this name already exists under the selected parent.';
end;
$$;

create or replace function public.propose_curriculum_node(
  p_parent_id uuid,
  p_node_type text,
  p_name text,
  p_description text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_type text := lower(btrim(coalesce(p_node_type, '')));
  normalized_name text := btrim(coalesce(p_name, ''));
  normalized_slug text;
  created_proposal public.curriculum_taxonomy_proposals%rowtype;
begin
  if caller_id is null
    or not public.authorization_user_has_capability(caller_id, 'taxonomy.propose')
  then
    raise exception 'Your assigned roles cannot propose curriculum nodes.';
  end if;
  if normalized_name = '' or length(normalized_name) > 140 then
    raise exception 'A curriculum node name between 1 and 140 characters is required.';
  end if;
  normalized_slug := public.normalize_curriculum_slug(normalized_name);
  if normalized_slug = '' then
    raise exception 'The curriculum node name must contain letters or numbers.';
  end if;
  perform public.assert_curriculum_parent(p_parent_id, normalized_type);

  if exists (
    select 1 from public.curriculum_nodes
    where parent_id is not distinct from p_parent_id
      and slug = normalized_slug
      and status = 'active'
  ) then
    raise exception 'This curriculum node already exists under the selected parent.';
  end if;
  if exists (
    select 1 from public.curriculum_taxonomy_proposals
    where parent_id is not distinct from p_parent_id
      and slug = normalized_slug
      and status = 'pending'
  ) then
    raise exception 'An equivalent curriculum proposal is already awaiting review.';
  end if;

  insert into public.curriculum_taxonomy_proposals (
    proposer_id, parent_id, node_type, name, slug, description
  ) values (
    caller_id, p_parent_id, normalized_type, normalized_name, normalized_slug,
    btrim(coalesce(p_description, ''))
  )
  returning * into created_proposal;

  insert into public.curriculum_taxonomy_events (
    event_type, proposal_id, actor_id, details
  ) values (
    'proposal_submitted', created_proposal.id, caller_id,
    jsonb_build_object('parentId', p_parent_id, 'nodeType', normalized_type)
  );
  return to_jsonb(created_proposal);
end;
$$;

create or replace function public.review_curriculum_proposal(
  p_proposal_id uuid,
  p_decision text,
  p_notes text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_decision text := lower(btrim(coalesce(p_decision, '')));
  normalized_notes text := btrim(coalesce(p_notes, ''));
  proposal public.curriculum_taxonomy_proposals%rowtype;
  created_node public.curriculum_nodes%rowtype;
begin
  if caller_id is null
    or not public.authorization_user_has_capability(caller_id, 'taxonomy.manage')
  then
    raise exception 'Only a taxonomy administrator can decide curriculum proposals.';
  end if;
  if normalized_decision not in ('approved', 'rejected') then
    raise exception 'The curriculum proposal decision must be approved or rejected.';
  end if;
  if normalized_decision = 'rejected' and normalized_notes = '' then
    raise exception 'Review notes are required when rejecting a curriculum proposal.';
  end if;

  select * into proposal
  from public.curriculum_taxonomy_proposals
  where id = p_proposal_id
  for update;
  if not found then raise exception 'The curriculum proposal could not be found.'; end if;
  if proposal.status <> 'pending' then
    raise exception 'Only a pending curriculum proposal can receive a decision.';
  end if;

  if normalized_decision = 'approved' then
    perform public.assert_curriculum_parent(proposal.parent_id, proposal.node_type);
    insert into public.curriculum_nodes (
      parent_id, node_type, name, slug, description, sort_order,
      created_by, approved_by, source_proposal_id, metadata
    ) values (
      proposal.parent_id, proposal.node_type, proposal.name, proposal.slug,
      proposal.description, public.next_curriculum_sort_order(proposal.parent_id),
      proposal.proposer_id, caller_id, proposal.id,
      jsonb_build_object('creationMode', 'approved_proposal')
    )
    returning * into created_node;

    update public.curriculum_taxonomy_proposals
    set status = 'approved', reviewer_id = caller_id,
        review_notes = normalized_notes, applied_node_id = created_node.id,
        decided_at = clock_timestamp()
    where id = proposal.id
    returning * into proposal;

    insert into public.curriculum_taxonomy_events (
      event_type, node_id, proposal_id, actor_id, details
    ) values (
      'proposal_approved', created_node.id, proposal.id, caller_id,
      jsonb_build_object('proposerId', proposal.proposer_id)
    );
  else
    update public.curriculum_taxonomy_proposals
    set status = 'rejected', reviewer_id = caller_id,
        review_notes = normalized_notes, applied_node_id = null,
        decided_at = clock_timestamp()
    where id = proposal.id
    returning * into proposal;

    insert into public.curriculum_taxonomy_events (
      event_type, proposal_id, actor_id, details
    ) values (
      'proposal_rejected', proposal.id, caller_id,
      jsonb_build_object('proposerId', proposal.proposer_id)
    );
  end if;

  return jsonb_build_object(
    'proposal', to_jsonb(proposal),
    'node', case when created_node.id is null then null else to_jsonb(created_node) end
  );
exception
  when unique_violation then
    raise exception 'An active curriculum node with this name already exists under the selected parent.';
end;
$$;

create or replace function public.update_curriculum_node(
  p_node_id uuid,
  p_name text,
  p_description text default '',
  p_sort_order integer default 100
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_name text := btrim(coalesce(p_name, ''));
  normalized_slug text;
  updated_node public.curriculum_nodes%rowtype;
begin
  if caller_id is null
    or not public.authorization_user_has_capability(caller_id, 'taxonomy.manage')
  then
    raise exception 'Only a taxonomy administrator can update canonical curriculum nodes.';
  end if;
  if normalized_name = '' or length(normalized_name) > 140 then
    raise exception 'A curriculum node name between 1 and 140 characters is required.';
  end if;
  normalized_slug := public.normalize_curriculum_slug(normalized_name);
  if normalized_slug = '' then
    raise exception 'The curriculum node name must contain letters or numbers.';
  end if;

  update public.curriculum_nodes
  set name = normalized_name,
      slug = normalized_slug,
      description = btrim(coalesce(p_description, '')),
      sort_order = greatest(coalesce(p_sort_order, 100), 0),
      updated_at = clock_timestamp()
  where id = p_node_id and status = 'active'
  returning * into updated_node;
  if not found then raise exception 'The active curriculum node could not be found.'; end if;

  insert into public.curriculum_taxonomy_events (
    event_type, node_id, actor_id, details
  ) values ('node_updated', updated_node.id, caller_id, '{}'::jsonb);
  return to_jsonb(updated_node);
exception
  when unique_violation then
    raise exception 'An active curriculum node with this name already exists under the selected parent.';
end;
$$;

create or replace function public.archive_curriculum_node(p_node_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  archived_node public.curriculum_nodes%rowtype;
begin
  if caller_id is null
    or not public.authorization_user_has_capability(caller_id, 'taxonomy.manage')
  then
    raise exception 'Only a taxonomy administrator can archive curriculum nodes.';
  end if;
  if exists (
    select 1 from public.curriculum_nodes
    where parent_id = p_node_id and status = 'active'
  ) then
    raise exception 'Archive this node''s active children first.';
  end if;

  update public.curriculum_nodes
  set status = 'archived', archived_at = clock_timestamp(), updated_at = clock_timestamp()
  where id = p_node_id and status = 'active'
  returning * into archived_node;
  if not found then raise exception 'The active curriculum node could not be found.'; end if;

  insert into public.curriculum_taxonomy_events (
    event_type, node_id, actor_id, details
  ) values ('node_archived', archived_node.id, caller_id, '{}'::jsonb);
  return to_jsonb(archived_node);
end;
$$;

-- A small system seed makes the hierarchy immediately testable without trying to
-- define Kelp's complete academic vocabulary in this migration.
insert into public.curriculum_nodes (
  id, parent_id, node_type, name, slug, description, sort_order, metadata
)
values
  ('10000000-0000-4000-8000-000000000001', null, 'degree', 'Middle School', 'middle-school', 'Middle-school curriculum.', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000002', null, 'degree', 'High School', 'high-school', 'High-school curriculum.', 20, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000003', null, 'degree', 'College', 'college', 'College-level curriculum.', 30, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000011', '10000000-0000-4000-8000-000000000001', 'subject', 'Mathematics', 'mathematics', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000012', '10000000-0000-4000-8000-000000000002', 'subject', 'Mathematics', 'mathematics', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000013', '10000000-0000-4000-8000-000000000002', 'subject', 'Physics', 'physics', '', 20, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000014', '10000000-0000-4000-8000-000000000003', 'subject', 'Mathematics', 'mathematics', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000021', '10000000-0000-4000-8000-000000000011', 'track', 'Pre-Algebra', 'pre-algebra', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000022', '10000000-0000-4000-8000-000000000012', 'track', 'Algebra 1', 'algebra-1', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000023', '10000000-0000-4000-8000-000000000013', 'track', 'Physics', 'physics', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000024', '10000000-0000-4000-8000-000000000014', 'track', 'Calculus I', 'calculus-1', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000031', '10000000-0000-4000-8000-000000000022', 'topic', 'Linear equations', 'linear-equations', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000032', '10000000-0000-4000-8000-000000000023', 'topic', 'Mechanics', 'mechanics', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000041', '10000000-0000-4000-8000-000000000032', 'topic', 'Kinematics', 'kinematics', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000051', '10000000-0000-4000-8000-000000000041', 'topic', 'Two-dimensional motion', 'two-dimensional-motion', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000061', '10000000-0000-4000-8000-000000000051', 'topic', 'Velocity', 'velocity', '', 10, '{"seed":true}'),
  ('10000000-0000-4000-8000-000000000062', '10000000-0000-4000-8000-000000000051', 'topic', 'Acceleration', 'acceleration', '', 20, '{"seed":true}')
on conflict (id) do nothing;

alter table public.curriculum_nodes enable row level security;
alter table public.curriculum_taxonomy_proposals enable row level security;
alter table public.curriculum_taxonomy_events enable row level security;

drop policy if exists "Authenticated users can read active curriculum nodes" on public.curriculum_nodes;
create policy "Authenticated users can read active curriculum nodes"
on public.curriculum_nodes for select to authenticated
using (
  status = 'active'
  or public.current_user_has_capability('taxonomy.manage')
);

drop policy if exists "Participants can read curriculum proposals" on public.curriculum_taxonomy_proposals;
create policy "Participants can read curriculum proposals"
on public.curriculum_taxonomy_proposals for select to authenticated
using (
  proposer_id = (select auth.uid())
  or public.current_user_has_capability('taxonomy.manage')
);

drop policy if exists "Taxonomy managers can read taxonomy events" on public.curriculum_taxonomy_events;
create policy "Taxonomy managers can read taxonomy events"
on public.curriculum_taxonomy_events for select to authenticated
using (public.current_user_has_capability('taxonomy.manage'));

revoke all on public.curriculum_nodes from anon, authenticated;
revoke all on public.curriculum_taxonomy_proposals from anon, authenticated;
revoke all on public.curriculum_taxonomy_events from anon, authenticated;
grant select on public.curriculum_nodes to authenticated;
grant select on public.curriculum_taxonomy_proposals to authenticated;
grant select on public.curriculum_taxonomy_events to authenticated;

revoke all on function public.normalize_curriculum_slug(text) from public, anon, authenticated;
revoke all on function public.assert_curriculum_parent(uuid, text) from public, anon, authenticated;
revoke all on function public.next_curriculum_sort_order(uuid) from public, anon, authenticated;
revoke all on function public.create_curriculum_node(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.propose_curriculum_node(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.review_curriculum_proposal(uuid, text, text) from public, anon, authenticated;
revoke all on function public.update_curriculum_node(uuid, text, text, integer) from public, anon, authenticated;
revoke all on function public.archive_curriculum_node(uuid) from public, anon, authenticated;
grant execute on function public.create_curriculum_node(uuid, text, text, text) to authenticated;
grant execute on function public.propose_curriculum_node(uuid, text, text, text) to authenticated;
grant execute on function public.review_curriculum_proposal(uuid, text, text) to authenticated;
grant execute on function public.update_curriculum_node(uuid, text, text, integer) to authenticated;
grant execute on function public.archive_curriculum_node(uuid) to authenticated;
