-- Phase 7.1: server-owned multi-role and capability foundation.
-- profiles.role remains a temporary primary-workspace hint only.

create table if not exists public.authorization_roles (
  role_key text primary key,
  display_name text not null,
  description text not null default '',
  sort_order integer not null default 100,
  is_system boolean not null default true,
  created_at timestamptz not null default now(),
  constraint authorization_roles_key_check check (
    role_key ~ '^[a-z][a-z0-9._-]{0,95}$'
  )
);

create table if not exists public.authorization_capabilities (
  capability_key text primary key,
  description text not null default '',
  created_at timestamptz not null default now(),
  constraint authorization_capabilities_key_check check (
    capability_key ~ '^[a-z][a-z0-9._-]{0,95}$'
  )
);

create table if not exists public.role_capabilities (
  role_key text not null references public.authorization_roles(role_key) on delete cascade,
  capability_key text not null references public.authorization_capabilities(capability_key) on delete cascade,
  granted_at timestamptz not null default now(),
  primary key (role_key, capability_key)
);

create table if not exists public.user_roles (
  user_id uuid not null references public.profiles(id) on delete cascade,
  role_key text not null references public.authorization_roles(role_key),
  status text not null default 'active',
  is_primary boolean not null default false,
  source text not null default 'admin',
  granted_by uuid,
  granted_at timestamptz not null default now(),
  revoked_by uuid,
  revoked_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  primary key (user_id, role_key),
  constraint user_roles_status_check check (status in ('active', 'revoked')),
  constraint user_roles_source_check check (source in ('legacy', 'signup', 'admin', 'credential', 'system')),
  constraint user_roles_metadata_check check (jsonb_typeof(metadata) = 'object'),
  constraint user_roles_revocation_check check (
    (status = 'active' and revoked_at is null and revoked_by is null)
    or (status = 'revoked' and revoked_at is not null)
  )
);

create unique index if not exists user_roles_one_primary_idx
on public.user_roles (user_id)
where status = 'active' and is_primary;

create index if not exists user_roles_active_role_idx
on public.user_roles (role_key, user_id)
where status = 'active';

create table if not exists public.user_credentials (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  credential_type text not null,
  title text not null default '',
  field_of_study text not null default '',
  institution text not null default '',
  country text not null default '',
  verification_status text not null default 'pending',
  evidence_reference text,
  submitted_at timestamptz not null default now(),
  reviewed_by uuid,
  reviewed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint user_credentials_type_present check (btrim(credential_type) <> ''),
  constraint user_credentials_status_check check (
    verification_status in ('pending', 'verified', 'rejected', 'expired')
  ),
  constraint user_credentials_review_check check (
    (verification_status = 'pending' and reviewed_by is null and reviewed_at is null)
    or (verification_status <> 'pending' and reviewed_by is not null and reviewed_at is not null)
  ),
  constraint user_credentials_metadata_check check (jsonb_typeof(metadata) = 'object')
);

create index if not exists user_credentials_user_status_idx
on public.user_credentials (user_id, verification_status, submitted_at desc);

create table if not exists public.authorization_events (
  id bigint generated by default as identity primary key,
  target_user_id uuid not null,
  actor_user_id uuid,
  role_key text not null,
  event_type text not null,
  reason text not null default '',
  occurred_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint authorization_events_role_present check (btrim(role_key) <> ''),
  constraint authorization_events_type_check check (
    event_type in ('granted', 'regranted', 'revoked', 'primary_selected')
  ),
  constraint authorization_events_metadata_check check (jsonb_typeof(metadata) = 'object')
);

create index if not exists authorization_events_target_idx
on public.authorization_events (target_user_id, occurred_at desc);

insert into public.authorization_roles (role_key, display_name, description, sort_order)
values
  ('student', 'Student', 'Participates in assigned or available learning experiences.', 10),
  ('tutor', 'Tutor', 'Authors tutoring resources that require publication review.', 20),
  ('teacher', 'Teacher', 'Authors teaching resources after qualification verification.', 30),
  ('mentor', 'Mentor', 'Reviews tutor content and builds or publishes curriculum resources.', 40),
  ('admin', 'Administrator', 'Manages authorization, taxonomy, publication, and platform operations.', 50)
on conflict (role_key) do update set
  display_name = excluded.display_name,
  description = excluded.description,
  sort_order = excluded.sort_order;

insert into public.authorization_capabilities (capability_key, description)
values
  ('workspace.student', 'Open the student workspace.'),
  ('workspace.tutor', 'Open the tutor workspace.'),
  ('workspace.teacher', 'Open the teacher workspace.'),
  ('workspace.mentor', 'Open the mentor workspace.'),
  ('workspace.admin', 'Open the administrator workspace.'),
  ('practice.attempt', 'Attempt authorized practice activities.'),
  ('practice.results.view_own', 'Read the user''s own practice results.'),
  ('exam.create', 'Create and edit owned private exam drafts.'),
  ('exam.submit_review', 'Submit owned exam drafts for review.'),
  ('exam.review', 'Inspect and decide regular tutor exam submissions.'),
  ('exam.publish', 'Publish exams when the publication policy permits it.'),
  ('form.create', 'Create and edit owned private form drafts.'),
  ('form.submit_review', 'Submit owned form drafts for review.'),
  ('form.review', 'Inspect and decide regular tutor form submissions.'),
  ('form.publish', 'Publish forms when the publication policy permits it.'),
  ('course.create', 'Create and edit course drafts.'),
  ('course.publish', 'Publish courses when the publication policy permits it.'),
  ('taxonomy.propose', 'Propose curriculum taxonomy nodes.'),
  ('taxonomy.manage', 'Approve and manage curriculum taxonomy nodes.'),
  ('credentials.review', 'Review user qualifications and credentials.'),
  ('authorization.manage', 'Grant and revoke platform roles.')
on conflict (capability_key) do update set description = excluded.description;

insert into public.role_capabilities (role_key, capability_key)
values
  ('student', 'workspace.student'),
  ('student', 'practice.attempt'),
  ('student', 'practice.results.view_own'),
  ('tutor', 'workspace.tutor'),
  ('tutor', 'exam.create'),
  ('tutor', 'exam.submit_review'),
  ('tutor', 'form.create'),
  ('tutor', 'form.submit_review'),
  ('teacher', 'workspace.teacher'),
  ('teacher', 'exam.create'),
  ('teacher', 'exam.submit_review'),
  ('teacher', 'form.create'),
  ('teacher', 'form.submit_review'),
  ('mentor', 'workspace.mentor'),
  ('mentor', 'exam.create'),
  ('mentor', 'exam.submit_review'),
  ('mentor', 'exam.review'),
  ('mentor', 'exam.publish'),
  ('mentor', 'form.create'),
  ('mentor', 'form.submit_review'),
  ('mentor', 'form.review'),
  ('mentor', 'form.publish'),
  ('mentor', 'course.create'),
  ('mentor', 'course.publish'),
  ('mentor', 'taxonomy.propose'),
  ('admin', 'workspace.admin'),
  ('admin', 'exam.create'),
  ('admin', 'exam.submit_review'),
  ('admin', 'exam.review'),
  ('admin', 'exam.publish'),
  ('admin', 'form.create'),
  ('admin', 'form.submit_review'),
  ('admin', 'form.review'),
  ('admin', 'form.publish'),
  ('admin', 'course.create'),
  ('admin', 'course.publish'),
  ('admin', 'taxonomy.propose'),
  ('admin', 'taxonomy.manage'),
  ('admin', 'credentials.review'),
  ('admin', 'authorization.manage')
on conflict (role_key, capability_key) do nothing;

-- The legacy profile role was historically populated from public sign-up
-- metadata, so it is not a trusted authorization source. Existing accounts
-- enter the cumulative-role model as students and privileged roles must be
-- granted through the protected administration or bootstrap paths below.
-- The preceding migration's identity trigger still treats role as immutable,
-- so suspend only that trigger for this trusted one-time normalization.
alter table public.profiles disable trigger profiles_prevent_identity_changes;

update public.profiles
set role = 'student'
where role <> 'student';

alter table public.profiles enable trigger profiles_prevent_identity_changes;

insert into public.user_roles (
  user_id, role_key, status, is_primary, source, granted_at
)
select id, 'student', 'active', true, 'system', coalesce(created_at, now())
from public.profiles
on conflict (user_id, role_key) do nothing;

create or replace function public.seed_profile_role_assignment()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  insert into public.user_roles (
    user_id, role_key, status, is_primary, source, granted_at
  ) values (
    new.id, 'student', 'active', true, 'signup', clock_timestamp()
  )
  on conflict (user_id, role_key) do nothing;
  return new;
end;
$$;

create or replace function public.authorization_user_has_capability(
  p_user_id uuid,
  p_capability_key text
)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select coalesce(exists (
    select 1
    from public.user_roles ur
    join public.role_capabilities rc on rc.role_key = ur.role_key
    where ur.user_id = p_user_id
      and ur.status = 'active'
      and rc.capability_key = lower(btrim(coalesce(p_capability_key, '')))
  ), false);
$$;

create or replace function public.enforce_exam_definition_lifecycle()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  caller_is_reviewer boolean := false;
  review_transition_allowed boolean := false;
begin
  caller_is_reviewer := public.authorization_user_has_capability(caller_id, 'exam.review');
  if tg_op = 'INSERT' then
    if new.status <> 'active' or new.review_status <> 'draft' or new.visibility <> 'private' then
      raise exception 'New exams must begin as private drafts.';
    end if;
    new.created_at := coalesce(new.created_at, clock_timestamp());
    new.updated_at := new.created_at;
    new.archived_at := null;
    return new;
  end if;

  if new.id is distinct from old.id
    or new.owner_id is distinct from old.owner_id
    or new.created_at is distinct from old.created_at
  then
    raise exception 'Exam identity and ownership fields are immutable.';
  end if;
  if old.status = 'archived' then
    raise exception 'Archived exams cannot be overwritten. Open the exam as a copy instead.';
  end if;

  if new.review_status is distinct from old.review_status
    or new.visibility is distinct from old.visibility
  then
    review_transition_allowed := (
      old.review_status = 'draft'
      and new.review_status = 'pending_review'
      and new.visibility = 'private'
      and caller_id = old.owner_id
    ) or (
      old.review_status = 'pending_review'
      and new.review_status in ('approved', 'changes_requested', 'rejected')
      and new.visibility = case when new.review_status = 'approved' then 'public' else 'private' end
      and caller_is_reviewer
    );
    if not review_transition_allowed then
      raise exception 'The requested exam review transition is not permitted.';
    end if;
  end if;

  if new.status = 'archived' then
    if old.review_status <> 'draft'
      or new.review_status <> 'draft'
      or new.visibility <> 'private'
      or new.bundle is distinct from old.bundle
    then
      raise exception 'Only the unchanged private draft can be archived.';
    end if;
  elsif new.status <> 'active' then
    raise exception 'The requested exam lifecycle transition is invalid.';
  end if;

  if new.bundle is distinct from old.bundle
    and old.review_status <> 'draft'
    and not review_transition_allowed
  then
    raise exception 'An exam under review or already reviewed cannot be overwritten.';
  end if;

  new.updated_at := clock_timestamp();
  if new.status = 'archived' then new.archived_at := new.updated_at;
  else new.archived_at := null;
  end if;
  return new;
end;
$$;

create or replace function public.submit_exam_for_review(p_exam_id text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  source_exam public.exam_definitions%rowtype;
  submitted_exam public.exam_definitions%rowtype;
  trusted_bundle jsonb;
begin
  if caller_id is null then
    raise exception 'Authentication is required to submit an exam for review.';
  end if;
  if not public.authorization_user_has_capability(caller_id, 'exam.submit_review') then
    raise exception 'Your assigned roles cannot submit exams for review.';
  end if;
  select * into source_exam
  from public.exam_definitions
  where id = btrim(coalesce(p_exam_id, ''))
  for update;
  if not found then raise exception 'The exam could not be found.'; end if;
  if source_exam.owner_id <> caller_id then raise exception 'This exam belongs to another tutor.'; end if;
  if source_exam.status <> 'active'
    or source_exam.review_status <> 'draft'
    or source_exam.visibility <> 'private'
  then
    raise exception 'Only an active private draft can be submitted for review.';
  end if;
  if exists (
    select 1 from public.exam_questions
    where exam_id = source_exam.id
      and (difficulty = 'unclassified' or classification_status <> 'proposed')
  ) then
    raise exception 'Classify every question before submitting this exam for review.';
  end if;
  if not exists (select 1 from public.exam_questions where exam_id = source_exam.id) then
    raise exception 'Add at least one question before submitting this exam for review.';
  end if;

  trusted_bundle := public.set_exam_bundle_review_state(
    source_exam.bundle, 'pending_review', 'private', false
  );
  update public.exam_definitions
  set review_status = 'pending_review', visibility = 'private', bundle = trusted_bundle
  where id = source_exam.id
  returning * into submitted_exam;

  update public.exam_questions
  set review_status = 'pending_review', updated_at = submitted_exam.updated_at
  where exam_id = source_exam.id;

  return jsonb_build_object(
    'id', submitted_exam.id,
    'status', submitted_exam.status,
    'review_status', submitted_exam.review_status,
    'visibility', submitted_exam.visibility,
    'created_at', submitted_exam.created_at,
    'updated_at', submitted_exam.updated_at,
    'archived_at', submitted_exam.archived_at,
    'bundle', submitted_exam.bundle
  );
end;
$$;

create or replace function public.review_exam(
  p_exam_id text,
  p_decision text,
  p_notes text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_decision text := lower(btrim(coalesce(p_decision, '')));
  normalized_notes text := btrim(coalesce(p_notes, ''));
  source_exam public.exam_definitions%rowtype;
  reviewed_exam public.exam_definitions%rowtype;
  review_record public.exam_reviews%rowtype;
  trusted_bundle jsonb;
  next_visibility text;
begin
  if caller_id is null then raise exception 'Authentication is required to review an exam.'; end if;
  if not public.authorization_user_has_capability(caller_id, 'exam.review') then
    raise exception 'Your assigned roles cannot review exams.';
  end if;
  if normalized_decision not in ('approved', 'changes_requested', 'rejected') then
    raise exception 'The exam review decision is invalid.';
  end if;
  if normalized_decision <> 'approved' and normalized_notes = '' then
    raise exception 'Review notes are required when requesting changes or rejecting an exam.';
  end if;

  select * into source_exam
  from public.exam_definitions
  where id = btrim(coalesce(p_exam_id, ''))
  for update;
  if not found then raise exception 'The exam could not be found.'; end if;
  if source_exam.status <> 'active' or source_exam.review_status <> 'pending_review' then
    raise exception 'Only an exam awaiting review can receive a decision.';
  end if;

  next_visibility := case when normalized_decision = 'approved' then 'public' else 'private' end;
  trusted_bundle := public.set_exam_bundle_review_state(
    source_exam.bundle,
    normalized_decision,
    next_visibility,
    normalized_decision = 'approved'
  );
  update public.exam_definitions
  set review_status = normalized_decision,
      visibility = next_visibility,
      bundle = trusted_bundle
  where id = source_exam.id
  returning * into reviewed_exam;

  update public.exam_questions
  set review_status = normalized_decision,
      classification_status = case
        when normalized_decision = 'approved' then 'reviewed'
        else classification_status
      end,
      content = case
        when normalized_decision = 'approved'
          then jsonb_set(content, '{classificationStatus}', to_jsonb('reviewed'::text), true)
        else content
      end,
      updated_at = reviewed_exam.updated_at
  where exam_id = source_exam.id;

  insert into public.exam_reviews (
    exam_id, owner_id, reviewer_id, decision, notes, reviewed_at
  ) values (
    source_exam.id,
    source_exam.owner_id,
    caller_id,
    normalized_decision,
    normalized_notes,
    reviewed_exam.updated_at
  )
  returning * into review_record;

  return jsonb_build_object(
    'exam', jsonb_build_object(
      'id', reviewed_exam.id,
      'status', reviewed_exam.status,
      'review_status', reviewed_exam.review_status,
      'visibility', reviewed_exam.visibility,
      'created_at', reviewed_exam.created_at,
      'updated_at', reviewed_exam.updated_at,
      'archived_at', reviewed_exam.archived_at,
      'bundle', reviewed_exam.bundle
    ),
    'review', jsonb_build_object(
      'id', review_record.id,
      'exam_id', review_record.exam_id,
      'owner_id', review_record.owner_id,
      'reviewer_id', review_record.reviewer_id,
      'decision', review_record.decision,
      'notes', review_record.notes,
      'reviewed_at', review_record.reviewed_at
    )
  );
end;
$$;

revoke all on function public.save_exam_draft(jsonb) from public, anon, authenticated;
revoke all on function public.submit_exam_for_review(text) from public, anon, authenticated;
revoke all on function public.review_exam(text, text, text) from public, anon, authenticated;
grant execute on function public.save_exam_draft(jsonb) to authenticated;
grant execute on function public.submit_exam_for_review(text) to authenticated;
grant execute on function public.review_exam(text, text, text) to authenticated;

drop trigger if exists profiles_seed_role_assignment on public.profiles;
create trigger profiles_seed_role_assignment
after insert on public.profiles
for each row
execute function public.seed_profile_role_assignment();

-- Signup metadata is profile data, not an authorization grant.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  insert into public.profiles (
    id, full_name, email, role, birth_date
  ) values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.email, ''),
    'student',
    nullif(new.raw_user_meta_data ->> 'birth_date', '')::date
  )
  on conflict (id) do update set
    full_name = excluded.full_name,
    email = excluded.email,
    birth_date = excluded.birth_date;
  return new;
end;
$$;

alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles drop constraint if exists profiles_role_key_check;
alter table public.profiles add constraint profiles_role_key_check check (
  role ~ '^[a-z][a-z0-9._-]{0,95}$'
);

create or replace function public.prevent_profile_identity_changes()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  if new.id is distinct from old.id or new.email is distinct from old.email then
    raise exception 'Profile identity fields cannot be changed through this client.';
  end if;
  return new;
end;
$$;

create or replace function public.authorization_user_has_capability(
  p_user_id uuid,
  p_capability_key text
)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select coalesce(exists (
    select 1
    from public.user_roles ur
    join public.role_capabilities rc on rc.role_key = ur.role_key
    where ur.user_id = p_user_id
      and ur.status = 'active'
      and rc.capability_key = lower(btrim(coalesce(p_capability_key, '')))
  ), false);
$$;

create or replace function public.current_user_has_role(p_role_key text)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select coalesce(exists (
    select 1 from public.user_roles
    where user_id = auth.uid()
      and status = 'active'
      and role_key = lower(btrim(coalesce(p_role_key, '')))
  ), false);
$$;

create or replace function public.current_user_has_capability(p_capability_key text)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select public.authorization_user_has_capability(
    auth.uid(),
    lower(btrim(coalesce(p_capability_key, '')))
  );
$$;

create or replace function public.get_my_authorization()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  role_keys text[] := array[]::text[];
  capability_keys text[] := array[]::text[];
  primary_role text;
begin
  if caller_id is null then
    raise exception 'Authentication is required to load authorization.';
  end if;

  select coalesce(array_agg(ur.role_key order by ar.sort_order, ur.role_key), array[]::text[])
  into role_keys
  from public.user_roles ur
  join public.authorization_roles ar on ar.role_key = ur.role_key
  where ur.user_id = caller_id and ur.status = 'active';

  select ur.role_key
  into primary_role
  from public.user_roles ur
  join public.authorization_roles ar on ar.role_key = ur.role_key
  where ur.user_id = caller_id and ur.status = 'active'
  order by ur.is_primary desc, ar.sort_order, ur.role_key
  limit 1;

  if coalesce(cardinality(role_keys), 0) = 0 then
    select role into primary_role from public.profiles where id = caller_id;
    role_keys := array[coalesce(primary_role, 'student')];
  end if;

  select coalesce(array_agg(distinct rc.capability_key order by rc.capability_key), array[]::text[])
  into capability_keys
  from public.role_capabilities rc
  where rc.role_key = any(role_keys);

  return jsonb_build_object(
    'version', 1,
    'primaryRole', coalesce(primary_role, role_keys[1], 'student'),
    'roles', to_jsonb(role_keys),
    'capabilities', to_jsonb(capability_keys)
  );
end;
$$;

create or replace function public.set_my_primary_role(p_role_key text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_role text := lower(btrim(coalesce(p_role_key, '')));
begin
  if caller_id is null then raise exception 'Authentication is required.'; end if;
  if not exists (
    select 1 from public.user_roles
    where user_id = caller_id and role_key = normalized_role and status = 'active'
  ) then
    raise exception 'The selected workspace role is not assigned to this user.';
  end if;

  update public.user_roles set is_primary = false
  where user_id = caller_id and status = 'active' and is_primary;
  update public.user_roles set is_primary = true
  where user_id = caller_id and role_key = normalized_role and status = 'active';
  update public.profiles set role = normalized_role where id = caller_id;
  insert into public.authorization_events (
    target_user_id, actor_user_id, role_key, event_type
  ) values (caller_id, caller_id, normalized_role, 'primary_selected');
  return public.get_my_authorization();
end;
$$;

create or replace function public.grant_user_role(
  p_user_id uuid,
  p_role_key text,
  p_reason text default '',
  p_make_primary boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_role text := lower(btrim(coalesce(p_role_key, '')));
  prior_status text;
  should_be_primary boolean := coalesce(p_make_primary, false);
begin
  if caller_id is null or not public.authorization_user_has_capability(caller_id, 'authorization.manage') then
    raise exception 'Only an authorization administrator can grant roles.';
  end if;
  if not exists (select 1 from public.profiles where id = p_user_id) then
    raise exception 'The target user profile does not exist.';
  end if;
  if not exists (select 1 from public.authorization_roles where role_key = normalized_role) then
    raise exception 'The requested role does not exist.';
  end if;

  select status into prior_status from public.user_roles
  where user_id = p_user_id and role_key = normalized_role;
  if not exists (
    select 1 from public.user_roles
    where user_id = p_user_id and status = 'active' and is_primary
  ) then
    should_be_primary := true;
  end if;
  if should_be_primary then
    update public.user_roles set is_primary = false
    where user_id = p_user_id and status = 'active' and is_primary;
  end if;

  insert into public.user_roles (
    user_id, role_key, status, is_primary, source, granted_by, granted_at,
    revoked_by, revoked_at
  ) values (
    p_user_id, normalized_role, 'active', should_be_primary, 'admin', caller_id,
    clock_timestamp(), null, null
  )
  on conflict (user_id, role_key) do update set
    status = 'active',
    is_primary = excluded.is_primary or public.user_roles.is_primary,
    source = 'admin',
    granted_by = caller_id,
    granted_at = clock_timestamp(),
    revoked_by = null,
    revoked_at = null;

  if should_be_primary then
    update public.profiles set role = normalized_role where id = p_user_id;
  end if;
  insert into public.authorization_events (
    target_user_id, actor_user_id, role_key, event_type, reason
  ) values (
    p_user_id, caller_id, normalized_role,
    case when prior_status = 'revoked' then 'regranted' else 'granted' end,
    btrim(coalesce(p_reason, ''))
  );
  return jsonb_build_object('userId', p_user_id, 'role', normalized_role, 'status', 'active');
end;
$$;

create or replace function public.revoke_user_role(
  p_user_id uuid,
  p_role_key text,
  p_reason text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_role text := lower(btrim(coalesce(p_role_key, '')));
  was_primary boolean := false;
  replacement_role text;
begin
  if caller_id is null or not public.authorization_user_has_capability(caller_id, 'authorization.manage') then
    raise exception 'Only an authorization administrator can revoke roles.';
  end if;
  select is_primary into was_primary
  from public.user_roles
  where user_id = p_user_id and role_key = normalized_role and status = 'active';
  if not found then raise exception 'The target user does not have this active role.'; end if;
  if (select count(*) from public.user_roles where user_id = p_user_id and status = 'active') <= 1 then
    raise exception 'A user must retain at least one active role.';
  end if;

  update public.user_roles set
    status = 'revoked', is_primary = false, revoked_by = caller_id,
    revoked_at = clock_timestamp()
  where user_id = p_user_id and role_key = normalized_role;

  if was_primary then
    select ur.role_key into replacement_role
    from public.user_roles ur
    join public.authorization_roles ar on ar.role_key = ur.role_key
    where ur.user_id = p_user_id and ur.status = 'active'
    order by ar.sort_order, ur.role_key
    limit 1;
    update public.user_roles set is_primary = true
    where user_id = p_user_id and role_key = replacement_role;
    update public.profiles set role = replacement_role where id = p_user_id;
  end if;

  insert into public.authorization_events (
    target_user_id, actor_user_id, role_key, event_type, reason
  ) values (
    p_user_id, caller_id, normalized_role, 'revoked', btrim(coalesce(p_reason, ''))
  );
  return jsonb_build_object('userId', p_user_id, 'role', normalized_role, 'status', 'revoked');
end;
$$;

-- One service-role-only recovery path establishes the first administrator
-- after public sign-up has created a student profile. The function refuses to
-- run once any active administrator exists and records the trusted bootstrap.
create or replace function public.bootstrap_first_administrator(
  p_user_id uuid,
  p_reason text default 'Initial trusted administrator bootstrap'
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  prior_status text;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'The first administrator can only be bootstrapped by the service role.';
  end if;

  -- Serialize the one-time check so concurrent trusted bootstrap requests
  -- cannot both observe an empty administrator set.
  perform pg_advisory_xact_lock(hashtext('public.bootstrap_first_administrator'));

  if p_user_id is null or not exists (
    select 1 from public.profiles where id = p_user_id
  ) then
    raise exception 'The bootstrap target profile does not exist.';
  end if;
  if exists (
    select 1 from public.user_roles
    where role_key = 'admin' and status = 'active'
  ) then
    raise exception 'An active administrator already exists.';
  end if;

  select status into prior_status
  from public.user_roles
  where user_id = p_user_id and role_key = 'admin';

  update public.user_roles
  set is_primary = false
  where user_id = p_user_id and status = 'active' and is_primary;

  insert into public.user_roles (
    user_id, role_key, status, is_primary, source, granted_by, granted_at,
    revoked_by, revoked_at, metadata
  ) values (
    p_user_id, 'admin', 'active', true, 'system', null, clock_timestamp(),
    null, null, jsonb_build_object('bootstrap', true, 'trustedRole', 'service_role')
  )
  on conflict (user_id, role_key) do update set
    status = 'active',
    is_primary = true,
    source = 'system',
    granted_by = null,
    granted_at = clock_timestamp(),
    revoked_by = null,
    revoked_at = null,
    metadata = jsonb_build_object('bootstrap', true, 'trustedRole', 'service_role');

  update public.profiles set role = 'admin' where id = p_user_id;

  insert into public.authorization_events (
    target_user_id, actor_user_id, role_key, event_type, reason, metadata
  ) values (
    p_user_id,
    auth.uid(),
    'admin',
    case when prior_status = 'revoked' then 'regranted' else 'granted' end,
    btrim(coalesce(p_reason, '')),
    jsonb_build_object('bootstrap', true, 'trustedRole', 'service_role')
  );

  return jsonb_build_object(
    'userId', p_user_id,
    'role', 'admin',
    'status', 'active',
    'primary', true,
    'bootstrap', true
  );
end;
$$;

alter table public.authorization_roles enable row level security;
alter table public.authorization_capabilities enable row level security;
alter table public.role_capabilities enable row level security;
alter table public.user_roles enable row level security;
alter table public.user_credentials enable row level security;
alter table public.authorization_events enable row level security;

drop policy if exists "Authenticated users can read role catalog" on public.authorization_roles;
create policy "Authenticated users can read role catalog"
on public.authorization_roles for select to authenticated using (true);
drop policy if exists "Authenticated users can read capability catalog" on public.authorization_capabilities;
create policy "Authenticated users can read capability catalog"
on public.authorization_capabilities for select to authenticated using (true);
drop policy if exists "Authenticated users can read role capability catalog" on public.role_capabilities;
create policy "Authenticated users can read role capability catalog"
on public.role_capabilities for select to authenticated using (true);

drop policy if exists "Users and authorization admins can read role assignments" on public.user_roles;
create policy "Users and authorization admins can read role assignments"
on public.user_roles for select to authenticated
using (
  user_id = (select auth.uid())
  or public.current_user_has_capability('authorization.manage')
);

drop policy if exists "Users and credential reviewers can read credentials" on public.user_credentials;
create policy "Users and credential reviewers can read credentials"
on public.user_credentials for select to authenticated
using (
  user_id = (select auth.uid())
  or public.current_user_has_capability('credentials.review')
);

drop policy if exists "Participants can read authorization events" on public.authorization_events;
create policy "Participants can read authorization events"
on public.authorization_events for select to authenticated
using (
  target_user_id = (select auth.uid())
  or actor_user_id = (select auth.uid())
  or public.current_user_has_capability('authorization.manage')
);

revoke all on public.authorization_roles from anon, authenticated;
revoke all on public.authorization_capabilities from anon, authenticated;
revoke all on public.role_capabilities from anon, authenticated;
revoke all on public.user_roles from anon, authenticated;
revoke all on public.user_credentials from anon, authenticated;
revoke all on public.authorization_events from anon, authenticated;
grant select on public.authorization_roles to authenticated;
grant select on public.authorization_capabilities to authenticated;
grant select on public.role_capabilities to authenticated;
grant select on public.user_roles to authenticated;
grant select on public.user_credentials to authenticated;
grant select on public.authorization_events to authenticated;

revoke update on public.profiles from authenticated;
grant update (full_name, birth_date) on public.profiles to authenticated;

revoke all on function public.authorization_user_has_capability(uuid, text) from public, anon, authenticated;
revoke all on function public.current_user_has_role(text) from public, anon, authenticated;
revoke all on function public.current_user_has_capability(text) from public, anon, authenticated;
revoke all on function public.get_my_authorization() from public, anon, authenticated;
revoke all on function public.set_my_primary_role(text) from public, anon, authenticated;
revoke all on function public.grant_user_role(uuid, text, text, boolean) from public, anon, authenticated;
revoke all on function public.revoke_user_role(uuid, text, text) from public, anon, authenticated;
revoke all on function public.bootstrap_first_administrator(uuid, text) from public, anon, authenticated;
grant execute on function public.current_user_has_role(text) to authenticated;
grant execute on function public.current_user_has_capability(text) to authenticated;
grant execute on function public.get_my_authorization() to authenticated;
grant execute on function public.set_my_primary_role(text) to authenticated;
grant execute on function public.grant_user_role(uuid, text, text, boolean) to authenticated;
grant execute on function public.revoke_user_role(uuid, text, text) to authenticated;
grant execute on function public.bootstrap_first_administrator(uuid, text) to service_role;

-- Trigger entry points are never browser RPCs.
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.prevent_profile_identity_changes() from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.seed_profile_role_assignment() from public, anon, authenticated;
revoke all on function public.enforce_form_definition_lifecycle() from public, anon, authenticated;
revoke all on function public.prevent_form_submission_mutation() from public, anon, authenticated;
revoke all on function public.enforce_exam_definition_lifecycle() from public, anon, authenticated;

-- Upgrade existing RLS checks to capability checks.
drop policy if exists "Tutors can create their own forms" on public.form_definitions;
create policy "Authorized authors can create their own forms"
on public.form_definitions
for insert
to authenticated
with check (
  (select auth.uid()) = owner_id
  and status = 'active'
  and public.current_user_has_capability('form.create')
);

drop policy if exists "Owners and reviewers can read exams" on public.exam_definitions;
create policy "Owners and capable reviewers can read exams"
on public.exam_definitions
for select
to authenticated
using (
  (select auth.uid()) = owner_id
  or public.current_user_has_capability('exam.review')
);

drop policy if exists "Owners and reviewers can read exam questions" on public.exam_questions;
create policy "Owners and capable reviewers can read exam questions"
on public.exam_questions
for select
to authenticated
using (
  (select auth.uid()) = owner_id
  or public.current_user_has_capability('exam.review')
);

drop policy if exists "Participants can read related exam reviews" on public.exam_reviews;
create policy "Participants and capable reviewers can read exam reviews"
on public.exam_reviews
for select
to authenticated
using (
  (select auth.uid()) = owner_id
  or (select auth.uid()) = reviewer_id
  or public.current_user_has_capability('exam.review')
);

-- Replace the draft RPC so secondary authoring roles work even when the
-- user's primary workspace is Student.
create or replace function public.save_exam_draft(p_bundle jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  source_exam jsonb;
  source_exam_id text;
  existing_exam public.exam_definitions%rowtype;
  saved_exam public.exam_definitions%rowtype;
  question_record jsonb;
  trusted_question jsonb;
  trusted_content jsonb;
  trusted_questions jsonb := '[]'::jsonb;
  trusted_bundle jsonb;
  question_position integer;
  question_id text;
  question_difficulty text;
  question_classification text;
  question_ids text[] := array[]::text[];
  saved_at timestamptz := clock_timestamp();
  created_at timestamptz;
begin
  if caller_id is null then
    raise exception 'Authentication is required to save an exam.';
  end if;
  if not public.authorization_user_has_capability(caller_id, 'exam.create') then
    raise exception 'Your assigned roles cannot create or edit exams.';
  end if;

  if coalesce(jsonb_typeof(p_bundle), '') <> 'object'
    or coalesce(p_bundle ->> 'schema', '') <> 'kelp-exam-persistence-bundle-v1'
    or coalesce(jsonb_typeof(p_bundle -> 'exam'), '') <> 'object'
    or coalesce(jsonb_typeof(p_bundle -> 'questions'), '') <> 'array'
    or coalesce(jsonb_typeof(p_bundle #> '{exam,questionIds}'), '') <> 'array'
  then
    raise exception 'A valid exam persistence bundle is required.';
  end if;

  source_exam := p_bundle -> 'exam';
  source_exam_id := btrim(coalesce(source_exam ->> 'id', ''));
  if source_exam_id = ''
    or coalesce(source_exam ->> 'schema', '') <> 'kelp-exam-definition-v1'
  then
    raise exception 'The exam definition identity or schema is invalid.';
  end if;

  select * into existing_exam
  from public.exam_definitions
  where id = source_exam_id;

  if found then
    if existing_exam.owner_id <> caller_id then
      raise exception 'This exam belongs to another tutor.';
    end if;
    if existing_exam.status = 'archived' then
      raise exception 'Archived exams cannot be overwritten. Open the exam as a copy instead.';
    end if;
    if existing_exam.review_status <> 'draft' then
      raise exception 'An exam under review or already reviewed cannot be overwritten. Open it as a copy instead.';
    end if;
    created_at := existing_exam.created_at;
  else
    created_at := saved_at;
  end if;

  if jsonb_array_length(p_bundle #> '{exam,questionIds}') <> jsonb_array_length(p_bundle -> 'questions') then
    raise exception 'The exam question order does not match its question records.';
  end if;

  for question_record, question_position in
    select value, (ordinality - 1)::integer
    from jsonb_array_elements(p_bundle -> 'questions') with ordinality
  loop
    question_id := btrim(coalesce(question_record ->> 'id', ''));
    question_difficulty := lower(btrim(coalesce(question_record ->> 'difficulty', '')));
    if question_id = ''
      or coalesce(question_record ->> 'schema', '') <> 'kelp-exam-question-record-v1'
      or coalesce(question_record ->> 'examId', '') <> source_exam_id
      or coalesce(jsonb_typeof(question_record -> 'content'), '') <> 'object'
      or coalesce(question_record #>> '{content,id}', '') <> question_id
      or coalesce(source_exam #> '{questionIds}' ->> question_position, '') <> question_id
    then
      raise exception 'The exam contains an invalid or misordered question record.';
    end if;
    if question_id = any(question_ids) then
      raise exception 'Question IDs must be unique within an exam.';
    end if;
    if question_difficulty not in ('unclassified', 'very-easy', 'easy', 'difficult', 'very-difficult', 'challenge') then
      raise exception 'The exam contains an unsupported question difficulty.';
    end if;

    question_classification := case
      when question_difficulty = 'unclassified' then 'unclassified'
      else 'proposed'
    end;
    question_ids := array_append(question_ids, question_id);

    trusted_content := question_record -> 'content';
    trusted_content := jsonb_set(trusted_content, '{id}', to_jsonb(question_id), true);
    trusted_content := jsonb_set(trusted_content, '{difficulty}', to_jsonb(question_difficulty), true);
    trusted_content := jsonb_set(trusted_content, '{classificationStatus}', to_jsonb(question_classification), true);

    trusted_question := question_record;
    trusted_question := jsonb_set(trusted_question, '{position}', to_jsonb(question_position), true);
    trusted_question := jsonb_set(trusted_question, '{createdBy}', to_jsonb(caller_id::text), true);
    trusted_question := jsonb_set(trusted_question, '{difficulty}', to_jsonb(question_difficulty), true);
    trusted_question := jsonb_set(trusted_question, '{classificationStatus}', to_jsonb(question_classification), true);
    trusted_question := jsonb_set(trusted_question, '{reviewStatus}', to_jsonb('draft'::text), true);
    trusted_question := jsonb_set(trusted_question, '{content}', trusted_content, true);
    trusted_questions := trusted_questions || jsonb_build_array(trusted_question);
  end loop;

  if exists (
    select 1 from public.exam_questions
    where id = any(question_ids) and exam_id <> source_exam_id
  ) then
    raise exception 'A question ID is already owned by another exam. Import or open the exam as an independent copy.';
  end if;

  source_exam := jsonb_set(source_exam, '{madeBy}', to_jsonb(caller_id::text), true);
  source_exam := jsonb_set(
    source_exam,
    '{createdAt}',
    to_jsonb(to_char(created_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    true
  );
  source_exam := jsonb_set(
    source_exam,
    '{updatedAt}',
    to_jsonb(to_char(saved_at at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')),
    true
  );
  trusted_bundle := jsonb_set(p_bundle, '{exam}', source_exam, true);
  trusted_bundle := jsonb_set(trusted_bundle, '{questions}', trusted_questions, true);
  trusted_bundle := jsonb_set(
    trusted_bundle,
    '{workflow}',
    jsonb_build_object('reviewStatus', 'draft', 'visibility', 'private'),
    true
  );

  insert into public.exam_definitions (
    id, owner_id, status, review_status, visibility, schema_version, title, bundle, created_at, updated_at, archived_at
  ) values (
    source_exam_id,
    caller_id,
    'active',
    'draft',
    'private',
    1,
    coalesce(source_exam ->> 'title', ''),
    trusted_bundle,
    created_at,
    saved_at,
    null
  )
  on conflict (id) do update set
    title = excluded.title,
    bundle = excluded.bundle,
    updated_at = excluded.updated_at,
    archived_at = null
  returning * into saved_exam;

  delete from public.exam_questions
  where exam_id = source_exam_id and not (id = any(question_ids));

  for trusted_question in select value from jsonb_array_elements(trusted_questions)
  loop
    insert into public.exam_questions (
      id,
      exam_id,
      owner_id,
      position,
      difficulty,
      classification_status,
      review_status,
      copied_from_question_id,
      content,
      created_at,
      updated_at
    ) values (
      trusted_question ->> 'id',
      source_exam_id,
      caller_id,
      (trusted_question ->> 'position')::integer,
      trusted_question ->> 'difficulty',
      trusted_question ->> 'classificationStatus',
      'draft',
      nullif(trusted_question ->> 'copiedFromQuestionId', ''),
      trusted_question -> 'content',
      saved_at,
      saved_at
    )
    on conflict (id) do update set
      position = excluded.position,
      difficulty = excluded.difficulty,
      classification_status = excluded.classification_status,
      review_status = 'draft',
      copied_from_question_id = excluded.copied_from_question_id,
      content = excluded.content,
      updated_at = excluded.updated_at;
  end loop;

  return jsonb_build_object(
    'id', saved_exam.id,
    'status', saved_exam.status,
    'review_status', saved_exam.review_status,
    'visibility', saved_exam.visibility,
    'created_at', saved_exam.created_at,
    'updated_at', saved_exam.updated_at,
    'archived_at', saved_exam.archived_at,
    'bundle', saved_exam.bundle
  );
end;
$$;
