create table if not exists public.exam_reviews (
  id bigint generated by default as identity primary key,
  exam_id text not null,
  owner_id uuid not null,
  reviewer_id uuid not null,
  decision text not null,
  notes text not null default '',
  reviewed_at timestamptz not null default now(),
  constraint exam_reviews_exam_id_present check (btrim(exam_id) <> ''),
  constraint exam_reviews_decision_check check (
    decision in ('approved', 'changes_requested', 'rejected')
  ),
  constraint exam_reviews_notes_check check (
    decision = 'approved' or btrim(notes) <> ''
  )
);

create index if not exists exam_reviews_exam_reviewed_idx
on public.exam_reviews (exam_id, reviewed_at desc);

create index if not exists exam_reviews_owner_reviewed_idx
on public.exam_reviews (owner_id, reviewed_at desc);

create or replace function public.set_exam_bundle_review_state(
  p_bundle jsonb,
  p_review_status text,
  p_visibility text,
  p_review_classifications boolean default false
)
returns jsonb
language plpgsql
immutable
set search_path = pg_catalog, public
as $$
declare
  question_record jsonb;
  trusted_question jsonb;
  trusted_content jsonb;
  trusted_questions jsonb := '[]'::jsonb;
  difficulty text;
  classification_status text;
  updated_bundle jsonb;
begin
  if p_review_status not in ('draft', 'pending_review', 'approved', 'changes_requested', 'rejected') then
    raise exception 'The exam review status is invalid.';
  end if;
  if p_visibility not in ('private', 'public')
    or (p_visibility = 'public' and p_review_status <> 'approved')
  then
    raise exception 'The exam visibility is invalid for this review state.';
  end if;
  if coalesce(jsonb_typeof(p_bundle -> 'questions'), '') <> 'array' then
    raise exception 'The exam bundle does not contain question records.';
  end if;

  for question_record in select value from jsonb_array_elements(p_bundle -> 'questions')
  loop
    difficulty := coalesce(question_record ->> 'difficulty', 'unclassified');
    classification_status := coalesce(question_record ->> 'classificationStatus', 'unclassified');
    if p_review_classifications then
      if difficulty = 'unclassified' then
        raise exception 'Every question needs a proposed difficulty before approval.';
      end if;
      classification_status := 'reviewed';
    end if;

    trusted_content := coalesce(question_record -> 'content', '{}'::jsonb);
    trusted_content := jsonb_set(trusted_content, '{difficulty}', to_jsonb(difficulty), true);
    trusted_content := jsonb_set(trusted_content, '{classificationStatus}', to_jsonb(classification_status), true);
    trusted_question := jsonb_set(question_record, '{reviewStatus}', to_jsonb(p_review_status), true);
    trusted_question := jsonb_set(trusted_question, '{classificationStatus}', to_jsonb(classification_status), true);
    trusted_question := jsonb_set(trusted_question, '{content}', trusted_content, true);
    trusted_questions := trusted_questions || jsonb_build_array(trusted_question);
  end loop;

  updated_bundle := jsonb_set(p_bundle, '{questions}', trusted_questions, true);
  updated_bundle := jsonb_set(
    updated_bundle,
    '{workflow}',
    jsonb_build_object('reviewStatus', p_review_status, 'visibility', p_visibility),
    true
  );
  return updated_bundle;
end;
$$;

create or replace function public.enforce_exam_definition_lifecycle()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  caller_is_reviewer boolean := false;
  review_transition_allowed boolean := false;
begin
  select exists (
    select 1 from public.profiles
    where id = caller_id and role in ('mentor', 'admin')
  ) into caller_is_reviewer;
  if tg_op = 'INSERT' then
    if new.status <> 'active' or new.review_status <> 'draft' or new.visibility <> 'private' then
      raise exception 'New exams must begin as private drafts.';
    end if;
    new.created_at := coalesce(new.created_at, clock_timestamp());
    new.updated_at := new.created_at;
    new.archived_at := null;
    return new;
  end if;

  if new.id is distinct from old.id
    or new.owner_id is distinct from old.owner_id
    or new.created_at is distinct from old.created_at
  then
    raise exception 'Exam identity and ownership fields are immutable.';
  end if;
  if old.status = 'archived' then
    raise exception 'Archived exams cannot be overwritten. Open the exam as a copy instead.';
  end if;

  if new.review_status is distinct from old.review_status
    or new.visibility is distinct from old.visibility
  then
    review_transition_allowed := (
      old.review_status = 'draft'
      and new.review_status = 'pending_review'
      and new.visibility = 'private'
      and caller_id = old.owner_id
    ) or (
      old.review_status = 'pending_review'
      and new.review_status in ('approved', 'changes_requested', 'rejected')
      and new.visibility = case when new.review_status = 'approved' then 'public' else 'private' end
      and caller_is_reviewer
    );
    if not review_transition_allowed then
      raise exception 'The requested exam review transition is not permitted.';
    end if;
  end if;

  if new.status = 'archived' then
    if old.review_status <> 'draft'
      or new.review_status <> 'draft'
      or new.visibility <> 'private'
      or new.bundle is distinct from old.bundle
    then
      raise exception 'Only the unchanged private draft can be archived.';
    end if;
  elsif new.status <> 'active' then
    raise exception 'The requested exam lifecycle transition is invalid.';
  end if;

  if new.bundle is distinct from old.bundle
    and old.review_status <> 'draft'
    and not review_transition_allowed
  then
    raise exception 'An exam under review or already reviewed cannot be overwritten.';
  end if;

  new.updated_at := clock_timestamp();
  if new.status = 'archived' then
    new.archived_at := new.updated_at;
  else
    new.archived_at := null;
  end if;
  return new;
end;
$$;

create or replace function public.submit_exam_for_review(p_exam_id text)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  source_exam public.exam_definitions%rowtype;
  submitted_exam public.exam_definitions%rowtype;
  trusted_bundle jsonb;
begin
  if caller_id is null then
    raise exception 'Authentication is required to submit an exam for review.';
  end if;
  select * into source_exam
  from public.exam_definitions
  where id = btrim(coalesce(p_exam_id, ''))
  for update;
  if not found then raise exception 'The exam could not be found.'; end if;
  if source_exam.owner_id <> caller_id then raise exception 'This exam belongs to another tutor.'; end if;
  if source_exam.status <> 'active'
    or source_exam.review_status <> 'draft'
    or source_exam.visibility <> 'private'
  then
    raise exception 'Only an active private draft can be submitted for review.';
  end if;
  if exists (
    select 1 from public.exam_questions
    where exam_id = source_exam.id
      and (difficulty = 'unclassified' or classification_status <> 'proposed')
  ) then
    raise exception 'Classify every question before submitting this exam for review.';
  end if;
  if not exists (
    select 1 from public.exam_questions where exam_id = source_exam.id
  ) then
    raise exception 'Add at least one question before submitting this exam for review.';
  end if;

  trusted_bundle := public.set_exam_bundle_review_state(
    source_exam.bundle,
    'pending_review',
    'private',
    false
  );
  update public.exam_definitions
  set review_status = 'pending_review', visibility = 'private', bundle = trusted_bundle
  where id = source_exam.id
  returning * into submitted_exam;

  update public.exam_questions
  set review_status = 'pending_review', updated_at = submitted_exam.updated_at
  where exam_id = source_exam.id;

  return jsonb_build_object(
    'id', submitted_exam.id,
    'status', submitted_exam.status,
    'review_status', submitted_exam.review_status,
    'visibility', submitted_exam.visibility,
    'created_at', submitted_exam.created_at,
    'updated_at', submitted_exam.updated_at,
    'archived_at', submitted_exam.archived_at,
    'bundle', submitted_exam.bundle
  );
end;
$$;

create or replace function public.review_exam(
  p_exam_id text,
  p_decision text,
  p_notes text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  caller_id uuid := auth.uid();
  normalized_decision text := lower(btrim(coalesce(p_decision, '')));
  normalized_notes text := btrim(coalesce(p_notes, ''));
  source_exam public.exam_definitions%rowtype;
  reviewed_exam public.exam_definitions%rowtype;
  review_record public.exam_reviews%rowtype;
  trusted_bundle jsonb;
  next_visibility text;
begin
  if caller_id is null then raise exception 'Authentication is required to review an exam.'; end if;
  if not exists (
    select 1 from public.profiles
    where id = caller_id and role in ('mentor', 'admin')
  ) then
    raise exception 'Only a mentor or administrator can review exams.';
  end if;
  if normalized_decision not in ('approved', 'changes_requested', 'rejected') then
    raise exception 'The exam review decision is invalid.';
  end if;
  if normalized_decision <> 'approved' and normalized_notes = '' then
    raise exception 'Review notes are required when requesting changes or rejecting an exam.';
  end if;

  select * into source_exam
  from public.exam_definitions
  where id = btrim(coalesce(p_exam_id, ''))
  for update;
  if not found then raise exception 'The exam could not be found.'; end if;
  if source_exam.status <> 'active' or source_exam.review_status <> 'pending_review' then
    raise exception 'Only an exam awaiting review can receive a decision.';
  end if;

  next_visibility := case when normalized_decision = 'approved' then 'public' else 'private' end;
  trusted_bundle := public.set_exam_bundle_review_state(
    source_exam.bundle,
    normalized_decision,
    next_visibility,
    normalized_decision = 'approved'
  );
  update public.exam_definitions
  set review_status = normalized_decision,
      visibility = next_visibility,
      bundle = trusted_bundle
  where id = source_exam.id
  returning * into reviewed_exam;

  update public.exam_questions
  set review_status = normalized_decision,
      classification_status = case
        when normalized_decision = 'approved' then 'reviewed'
        else classification_status
      end,
      content = case
        when normalized_decision = 'approved'
          then jsonb_set(content, '{classificationStatus}', to_jsonb('reviewed'::text), true)
        else content
      end,
      updated_at = reviewed_exam.updated_at
  where exam_id = source_exam.id;

  insert into public.exam_reviews (
    exam_id, owner_id, reviewer_id, decision, notes, reviewed_at
  ) values (
    source_exam.id,
    source_exam.owner_id,
    caller_id,
    normalized_decision,
    normalized_notes,
    reviewed_exam.updated_at
  )
  returning * into review_record;

  return jsonb_build_object(
    'exam', jsonb_build_object(
      'id', reviewed_exam.id,
      'status', reviewed_exam.status,
      'review_status', reviewed_exam.review_status,
      'visibility', reviewed_exam.visibility,
      'created_at', reviewed_exam.created_at,
      'updated_at', reviewed_exam.updated_at,
      'archived_at', reviewed_exam.archived_at,
      'bundle', reviewed_exam.bundle
    ),
    'review', jsonb_build_object(
      'id', review_record.id,
      'exam_id', review_record.exam_id,
      'owner_id', review_record.owner_id,
      'reviewer_id', review_record.reviewer_id,
      'decision', review_record.decision,
      'notes', review_record.notes,
      'reviewed_at', review_record.reviewed_at
    )
  );
end;
$$;

alter table public.exam_reviews enable row level security;

drop policy if exists "Owners and reviewers can read exams" on public.exam_definitions;
drop policy if exists "Tutors can read their own exams" on public.exam_definitions;
create policy "Owners and reviewers can read exams"
on public.exam_definitions
for select
to authenticated
using (
  (select auth.uid()) = owner_id
  or exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role in ('mentor', 'admin')
  )
);

drop policy if exists "Owners and reviewers can read exam questions" on public.exam_questions;
drop policy if exists "Tutors can read questions from their own exams" on public.exam_questions;
create policy "Owners and reviewers can read exam questions"
on public.exam_questions
for select
to authenticated
using (
  (select auth.uid()) = owner_id
  or exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role in ('mentor', 'admin')
  )
);

drop policy if exists "Participants can read related exam reviews" on public.exam_reviews;
create policy "Participants can read related exam reviews"
on public.exam_reviews
for select
to authenticated
using (
  (select auth.uid()) = owner_id
  or (select auth.uid()) = reviewer_id
  or exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and role in ('mentor', 'admin')
  )
);

revoke all on public.exam_reviews from anon, authenticated;
grant select on public.exam_reviews to authenticated;

revoke all on function public.set_exam_bundle_review_state(jsonb, text, text, boolean) from public, anon, authenticated;
revoke all on function public.submit_exam_for_review(text) from public, anon, authenticated;
grant execute on function public.submit_exam_for_review(text) to authenticated;
revoke all on function public.review_exam(text, text, text) from public, anon, authenticated;
grant execute on function public.review_exam(text, text, text) to authenticated;
